export const DEFAULT_DRIVE_SEARCH_DRAFT = "Show me this file";

/** Clear only the untouched prompt generated by selecting a saved Drive result. */
export function clearGeneratedDriveSearchDraft(text: string, generated: boolean): string {
  return generated && text === DEFAULT_DRIVE_SEARCH_DRAFT ? "" : text;
}
