BEGIN;

DROP FUNCTION IF EXISTS repair_pkm_scope_exposure_revision_v1(TEXT, TEXT, INTEGER, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS commit_pkm_scope_exposure_v1(TEXT, TEXT, INTEGER, INTEGER, JSONB, JSONB, JSONB, JSONB, JSONB, JSONB);

COMMIT;
