import vector from "../fixtures/hermes-vault-vector.json";
import creationVector from "../fixtures/hermes-vault-creation-vector.json";

import { VaultService } from "@/lib/services/vault-service";
import {
  unlockVaultWithPassphrase,
  unlockVaultWithRecoveryKey,
} from "@/lib/vault/passphrase-key";

describe("Hermes vault crypto vector", () => {
  it("unwraps and hashes identically to the native bridge", async () => {
    const vaultKey = await unlockVaultWithPassphrase(
      vector.passphrase,
      vector.encrypted_vault_key_b64,
      vector.salt_b64,
      vector.iv_b64,
    );

    expect(vaultKey).toBe(vector.vault_key_hex);
    expect(await VaultService.hashVaultKey(vaultKey)).toBe(vector.vault_key_hash);
  });

  it("opens both first-vault wrappers generated by the Hermes-compatible contract", async () => {
    const fromPassphrase = await unlockVaultWithPassphrase(
      creationVector.passphrase,
      creationVector.passphrase_wrapper.encrypted_vault_key_b64,
      creationVector.passphrase_wrapper.salt_b64,
      creationVector.passphrase_wrapper.iv_b64,
    );
    const fromRecovery = await unlockVaultWithRecoveryKey(
      creationVector.recovery_key,
      creationVector.recovery_wrapper.encrypted_vault_key_b64,
      creationVector.recovery_wrapper.salt_b64,
      creationVector.recovery_wrapper.iv_b64,
    );

    expect(fromPassphrase).toBe(creationVector.vault_key_hex);
    expect(fromRecovery).toBe(creationVector.vault_key_hex);
    expect(await VaultService.hashVaultKey(fromPassphrase)).toBe(
      creationVector.vault_key_hash,
    );
  });
});
