"""The advisor directory's base URL must survive a deploy.

BACKEND_RUNTIME_CONFIG_JSON is regenerated by
scripts/ops/sync_backend_runtime_secrets.py on every deploy, so a value only
written into Secret Manager by hand is overwritten on the next release and the
surface silently reports "not configured". These tests pin both halves of the
path: the generator emits the key, and the runtime maps it onto the env var the
service reads.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import pytest

from hushh_mcp import runtime_settings
from hushh_mcp.services import advisor_directory_service as ads

_SYNC_SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "ops" / "sync_backend_runtime_secrets.py"
)

_CONFIG_ARGS = (
    "environment project db_host db_port db_name db_unix_socket "
    "cloudsql_instance_connection_name consent_sse_enabled sync_remote_enabled "
    "developer_api_enabled remote_mcp_enabled cors_allowed_origins "
    "obs_data_stale_ratio_threshold passkey_allowed_rp_ids plaid_env "
    "plaid_client_name plaid_country_codes plaid_webhook_url plaid_redirect_path "
    "plaid_redirect_uri plaid_tx_history_days one_location_read_only_state_enabled "
    "one_location_nearby_presence_mode one_location_nearby_presence_cohort "
    "consent_center_summary_v2_enabled db_bulk_batching_enabled "
    "hushh_trusted_device_enabled hushh_trusted_device_uat_allowlist "
    "advisors_api_base_url advisors_api_key_source_project "
    "advisors_api_key_source_secret insurance_agents_api_base_url "
    "insurance_agents_api_key_source_project insurance_agents_api_key_source_secret "
    "one_places_directory_enabled nws_nearby_api_base_url "
    "nws_nearby_api_key_source_project nws_nearby_api_key_source_secret "
    "nws_nearby_v4_api_base_url nws_nearby_v4_api_key_source_project "
    "nws_nearby_v4_api_key_source_secret"
).split()


def _load_sync_module():
    spec = importlib.util.spec_from_file_location("sync_backend_runtime_secrets", _SYNC_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _namespace(**overrides) -> argparse.Namespace:
    values = dict.fromkeys(_CONFIG_ARGS, "")
    values.update({"environment": "uat", "project": "hushh-pda-uat"})
    values.update(overrides)
    return argparse.Namespace(**values)


def test_generated_runtime_config_carries_the_advisors_base_url():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(
        _namespace(advisors_api_base_url="https://advisors.example")
    )
    assert config["advisors_api_base_url"] == "https://advisors.example"


def test_a_blank_base_url_is_omitted_so_unconfigured_lanes_stay_inert():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(_namespace(advisors_api_base_url=""))
    assert "advisors_api_base_url" not in config


def test_runtime_config_hydrates_the_env_var_the_service_reads(monkeypatch):
    monkeypatch.delenv("ADVISORS_API_BASE_URL", raising=False)
    monkeypatch.delenv("ADVISORS_API_BASE", raising=False)
    monkeypatch.setenv(
        "BACKEND_RUNTIME_CONFIG_JSON",
        json.dumps({"advisors_api_base_url": "https://advisors.example"}),
    )

    runtime_settings.hydrate_runtime_environment()

    assert ads.base_url() == "https://advisors.example"


def test_the_service_reports_unavailable_without_a_key(monkeypatch):
    monkeypatch.setenv("ADVISORS_API_BASE_URL", "https://advisors.example")
    monkeypatch.delenv("ADVISORS_API_KEY", raising=False)

    assert ads.is_configured() is False


def test_the_directory_key_is_mirrored_from_its_home_project(monkeypatch):
    """A hand-copied key does not follow a rotation; a mirrored one does.

    The source rotated and disabled the old version while UAT still held the
    copy, so the surface answered 502 with a revoked credential.
    """
    module = _load_sync_module()
    reads: list[tuple[str, str]] = []
    writes: list[tuple[str, str, str]] = []

    def fake_read(project: str, secret: str) -> str:
        reads.append((project, secret))
        if (project, secret) == ("hushh-tech-prod", "brokercheck-api-key"):
            return "rotated-key"
        return "stale-key"

    monkeypatch.setattr(module, "_read_secret", fake_read)
    monkeypatch.setattr(module, "_upsert_secret", lambda p, s, v: writes.append((p, s, v)))

    status = module._mirror_directory_key(
        target_project="hushh-pda-uat",
        target_secret="ADVISORS_API_KEY",  # noqa: S106
        source_project="hushh-tech-prod",
        # noqa comment: this is a secret *name*, not a credential value.
        source_secret="brokercheck-api-key",  # noqa: S106
    )

    assert ("hushh-tech-prod", "brokercheck-api-key") in reads
    assert writes == [("hushh-pda-uat", "ADVISORS_API_KEY", "rotated-key")]
    assert status and "rotated" in status


def test_an_unchanged_key_does_not_mint_a_secret_version(monkeypatch):
    """The shared upsert helper adds a version unconditionally."""
    module = _load_sync_module()
    writes: list = []

    monkeypatch.setattr(module, "_read_secret", lambda project, secret: "same-key")
    monkeypatch.setattr(module, "_upsert_secret", lambda p, s, v: writes.append(s))

    status = module._mirror_directory_key(
        target_project="hushh-pda-uat",
        target_secret="ADVISORS_API_KEY",  # noqa: S106
        source_project="hushh-tech-prod",
        # noqa comment: this is a secret *name*, not a credential value.
        source_secret="brokercheck-api-key",  # noqa: S106
    )

    assert writes == []
    assert status and "unchanged" in status


def test_a_lane_without_access_to_the_source_is_left_inert(monkeypatch):
    """A dev lane with no cross-project read must not fail its deploy."""
    module = _load_sync_module()

    monkeypatch.setattr(module, "_read_secret", lambda project, secret: "")
    monkeypatch.setattr(
        module,
        "_upsert_secret",
        lambda *a: pytest.fail("must not write without a source value"),
    )

    assert (
        module._mirror_directory_key(
            target_project="hushh-pda-uat",
            target_secret="ADVISORS_API_KEY",  # noqa: S106
            source_project="hushh-tech-prod",
            # noqa comment: this is a secret *name*, not a credential value.
            source_secret="brokercheck-api-key",  # noqa: S106
        )
        is None
    )


def test_the_deploy_workflows_pass_the_flag_they_configure():
    """A generator argument nobody passes is the same as no argument at all."""
    workflow = (
        Path(__file__).resolve().parents[2] / ".github" / "workflows" / "deploy-uat.yml"
    ).read_text()
    assert "--advisors-api-base-url" in workflow


@pytest.mark.parametrize("key", ["advisors_api_base_url"])
def test_runtime_env_map_owns_the_key(key):
    assert runtime_settings._BACKEND_RUNTIME_ENV_MAP[key] == "ADVISORS_API_BASE_URL"
