"""Connect Azure's hub settings must survive a dev deploy, and only a dev deploy.

BACKEND_RUNTIME_CONFIG_JSON is regenerated by
scripts/ops/sync_backend_runtime_secrets.py on every deploy, and the runtime
copies only the keys in ``_BACKEND_RUNTIME_ENV_MAP`` into the environment. Both
halves are pinned here: the generator emits the Azure keys for the dev
project with a return address derived from the dev origin, emits none for UAT
or production, and the runtime hydrates exactly the variables the Azure
services read.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import pytest

from hushh_mcp import runtime_settings
from hushh_mcp.services import azure_entra_authorizer, azure_federation, azure_image_source

_SYNC_SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "ops" / "sync_backend_runtime_secrets.py"
)
_AZURE_KEYS = {
    "hussh_azure_app_client_id": "HUSSH_AZURE_APP_CLIENT_ID",
    "hussh_azure_broker_sa": "HUSSH_AZURE_BROKER_SA",
    "hussh_azure_oauth_redirect_uri": "HUSSH_AZURE_OAUTH_REDIRECT_URI",
    "hussh_pod_image_reader_sa": "HUSSH_POD_IMAGE_READER_SA",
    "hussh_azure_pod_image_repository": "HUSSH_AZURE_POD_IMAGE_REPOSITORY",
}


_CONFIG_ARGS = (
    "db_host db_port db_name db_unix_socket cloudsql_instance_connection_name "
    "consent_sse_enabled sync_remote_enabled developer_api_enabled remote_mcp_enabled "
    "cors_allowed_origins obs_data_stale_ratio_threshold passkey_allowed_rp_ids plaid_env "
    "plaid_client_name plaid_country_codes plaid_webhook_url plaid_redirect_path "
    "plaid_redirect_uri plaid_tx_history_days one_location_read_only_state_enabled "
    "one_location_nearby_presence_mode one_location_nearby_presence_cohort "
    "consent_center_summary_v2_enabled db_bulk_batching_enabled "
    "hushh_trusted_device_enabled hushh_trusted_device_uat_allowlist "
    "advisors_api_base_url insurance_agents_api_base_url one_places_directory_enabled "
    "nws_nearby_api_base_url nws_nearby_v4_api_base_url"
).split()


def _load_sync_module():
    spec = importlib.util.spec_from_file_location("sync_backend_runtime_secrets", _SYNC_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _config(project: str, origin: str) -> dict:
    # Every other generator input is blank, which the generator drops.
    values = dict.fromkeys(_CONFIG_ARGS, "")
    values.update({"environment": "uat", "project": project, "app_frontend_origin": origin})
    return _load_sync_module()._build_backend_runtime_config(argparse.Namespace(**values))


def test_the_dev_lane_carries_every_azure_setting():
    config = _config("hushh-pda-dev", "https://dev.one.hushh.ai")

    assert {key: config[key] for key in _AZURE_KEYS} == {
        "hussh_azure_app_client_id": "4c6a5fc7-d4da-4061-ad27-b95fb125237b",
        "hussh_azure_broker_sa": "hussh-azure-broker@hushh-pda-dev.iam.gserviceaccount.com",
        "hussh_azure_oauth_redirect_uri": "https://dev.one.hushh.ai/one/setup/cloud/azure/return",
        "hussh_pod_image_reader_sa": "hussh-pod-image-reader@hushh-pda-dev.iam.gserviceaccount.com",
        "hussh_azure_pod_image_repository": (
            "us-central1-docker.pkg.dev/hushh-pda-dev/one-pod-release/consent-protocol-pod"
        ),
    }


@pytest.mark.parametrize("project", ["hushh-pda-uat", "hushh-pda", "some-other-project"])
def test_uat_and_production_carry_no_azure_settings(project):
    config = _config(project, "https://uat.one.hushh.ai")

    assert not set(_AZURE_KEYS) & set(config)


def test_the_return_address_follows_the_lane_origin_not_a_constant():
    config = _config("hushh-pda-dev", "https://dev.one.hushh.ai/")

    assert config["hussh_azure_oauth_redirect_uri"] == (
        "https://dev.one.hushh.ai/one/setup/cloud/azure/return"
    )
    with pytest.raises(ValueError):
        _config("hushh-pda-dev", "https://dev.one.hushh.ai/somewhere")


@pytest.mark.parametrize(("key", "env_name"), sorted(_AZURE_KEYS.items()))
def test_runtime_env_map_owns_each_key(key, env_name):
    assert runtime_settings._BACKEND_RUNTIME_ENV_MAP[key] == env_name


def test_hydration_gives_the_azure_services_their_settings(monkeypatch):
    # Hydration writes os.environ directly; registering each name with monkeypatch
    # first makes teardown remove it, so no later test inherits the dev settings.
    for env_name in _AZURE_KEYS.values():
        monkeypatch.setenv(env_name, "")
        monkeypatch.delenv(env_name)
    config = _config("hushh-pda-dev", "https://dev.one.hushh.ai")
    monkeypatch.setenv(runtime_settings.BACKEND_RUNTIME_CONFIG_JSON_ENV, json.dumps(config))

    runtime_settings.hydrate_runtime_environment()

    assert azure_federation.app_client_id() == "4c6a5fc7-d4da-4061-ad27-b95fb125237b"
    assert azure_federation.broker_service_account().startswith("hussh-azure-broker@")
    assert azure_entra_authorizer.redirect_uri().startswith("https://dev.one.hushh.ai/")
    assert azure_image_source.reader_service_account().startswith("hussh-pod-image-reader@")
    assert azure_image_source.release_source("gcr.io/p/i@sha256:" + "b" * 64).startswith(
        "us-central1-docker.pkg.dev/hushh-pda-dev/one-pod-release/"
    )
