"""The insurance agent directory's base URL and key must survive a deploy.

The sibling of test_advisors_runtime_config_wiring, and for the same reason:
BACKEND_RUNTIME_CONFIG_JSON is regenerated by
scripts/ops/sync_backend_runtime_secrets.py on every deploy, so a value only
written into Secret Manager by hand is overwritten on the next release and the
surface silently reports "not configured".

The key half matters even more here than for advisers. Read access to the home
project is a per-secret grant that does not come with any lane's own
project-level roles, so a lane that was never granted it mirrors nothing and
stays inert — which is correct, but only if the mirror is actually wired.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import pytest

from hushh_mcp import runtime_settings
from hushh_mcp.services import insurance_agent_directory_service as iads

_SYNC_SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "ops" / "sync_backend_runtime_secrets.py"
)

_CONFIG_ARGS = (
    "environment project db_host db_port db_name db_unix_socket "
    "cloudsql_instance_connection_name consent_sse_enabled sync_remote_enabled "
    "developer_api_enabled remote_mcp_enabled cors_allowed_origins "
    "obs_data_stale_ratio_threshold passkey_allowed_rp_ids plaid_env "
    "plaid_client_name plaid_country_codes plaid_webhook_url plaid_redirect_path "
    "plaid_redirect_uri plaid_tx_history_days one_location_read_only_state_enabled "
    "one_location_nearby_presence_mode one_location_nearby_presence_cohort "
    "consent_center_summary_v2_enabled db_bulk_batching_enabled "
    "hushh_trusted_device_enabled hushh_trusted_device_uat_allowlist "
    "advisors_api_base_url advisors_api_key_source_project "
    "advisors_api_key_source_secret insurance_agents_api_base_url "
    "insurance_agents_api_key_source_project insurance_agents_api_key_source_secret"
).split()


def _load_sync_module():
    spec = importlib.util.spec_from_file_location("sync_backend_runtime_secrets", _SYNC_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _namespace(**overrides) -> argparse.Namespace:
    values = dict.fromkeys(_CONFIG_ARGS, "")
    values.update({"environment": "uat", "project": "hushh-pda-uat"})
    values.update(overrides)
    return argparse.Namespace(**values)


def test_generated_runtime_config_carries_the_insurance_base_url():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(
        _namespace(insurance_agents_api_base_url="https://agents.example")
    )
    assert config["insurance_agents_api_base_url"] == "https://agents.example"


def test_a_blank_base_url_is_omitted_so_unconfigured_lanes_stay_inert():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(_namespace())
    assert "insurance_agents_api_base_url" not in config


def test_adding_this_directory_did_not_displace_the_advisor_one():
    """Both directories share one generated config blob and one mirror helper."""
    module = _load_sync_module()
    config = module._build_backend_runtime_config(
        _namespace(
            advisors_api_base_url="https://advisors.example",
            insurance_agents_api_base_url="https://agents.example",
        )
    )
    assert config["advisors_api_base_url"] == "https://advisors.example"
    assert config["insurance_agents_api_base_url"] == "https://agents.example"


def test_runtime_config_hydrates_the_env_var_the_service_reads(monkeypatch):
    monkeypatch.delenv("INSURANCE_AGENTS_API_BASE_URL", raising=False)
    monkeypatch.delenv("INSURANCE_AGENTS_API_BASE", raising=False)
    monkeypatch.setenv(
        "BACKEND_RUNTIME_CONFIG_JSON",
        json.dumps({"insurance_agents_api_base_url": "https://agents.example"}),
    )

    runtime_settings.hydrate_runtime_environment()

    assert iads.base_url() == "https://agents.example"


def test_the_service_reports_unavailable_without_a_key(monkeypatch):
    monkeypatch.setenv("INSURANCE_AGENTS_API_BASE_URL", "https://agents.example")
    monkeypatch.delenv("INSURANCE_AGENTS_API_KEY", raising=False)
    assert iads.is_configured() is False


def test_the_directory_key_is_mirrored_from_its_home_project(monkeypatch):
    module = _load_sync_module()
    reads: list[tuple[str, str]] = []
    writes: list[tuple[str, str, str]] = []

    def fake_read(project: str, secret: str) -> str:
        reads.append((project, secret))
        if (project, secret) == ("hushh-tech-prod", "insurance-agents-api-key"):
            return "rotated-key"
        return "stale-key"

    monkeypatch.setattr(module, "_read_secret", fake_read)
    monkeypatch.setattr(module, "_upsert_secret", lambda p, s, v: writes.append((p, s, v)))

    status = module._mirror_directory_key(
        target_project="hushh-pda-uat",
        target_secret="INSURANCE_AGENTS_API_KEY",  # noqa: S106
        source_project="hushh-tech-prod",
        # noqa comment: this is a secret *name*, not a credential value.
        source_secret="insurance-agents-api-key",  # noqa: S106
    )

    assert ("hushh-tech-prod", "insurance-agents-api-key") in reads
    assert writes == [("hushh-pda-uat", "INSURANCE_AGENTS_API_KEY", "rotated-key")]
    assert status and "rotated" in status


def test_a_lane_without_access_to_the_source_is_left_inert(monkeypatch):
    """Read access is a per-secret grant in the home project, so this is the
    real state of any lane that was never granted it — not a hypothetical."""
    module = _load_sync_module()

    monkeypatch.setattr(module, "_read_secret", lambda project, secret: "")
    monkeypatch.setattr(
        module,
        "_upsert_secret",
        lambda *a: pytest.fail("must not write without a source value"),
    )

    assert (
        module._mirror_directory_key(
            target_project="hushh-pda-uat",
            target_secret="INSURANCE_AGENTS_API_KEY",  # noqa: S106
            source_project="hushh-tech-prod",
            # noqa comment: this is a secret *name*, not a credential value.
            source_secret="insurance-agents-api-key",  # noqa: S106
        )
        is None
    )


def test_the_deploy_workflow_passes_the_flag_it_configures():
    """A generator argument nobody passes is the same as no argument at all."""
    workflow = (
        Path(__file__).resolve().parents[2] / ".github" / "workflows" / "deploy-uat.yml"
    ).read_text()
    assert "--insurance-agents-api-base-url" in workflow


def test_the_deploy_mounts_the_mirrored_key_on_the_backend():
    """A mirrored secret nothing binds never reaches the runtime."""
    cloudbuild = (
        Path(__file__).resolve().parents[2] / "deploy" / "backend.cloudbuild.yaml"
    ).read_text()
    assert "add_secret INSURANCE_AGENTS_API_KEY INSURANCE_AGENTS_API_KEY" in cloudbuild


def test_runtime_env_map_owns_the_key():
    assert (
        runtime_settings._BACKEND_RUNTIME_ENV_MAP["insurance_agents_api_base_url"]
        == "INSURANCE_AGENTS_API_BASE_URL"
    )
