"""The advisor directory's base URL must survive a deploy.

BACKEND_RUNTIME_CONFIG_JSON is regenerated by
scripts/ops/sync_backend_runtime_secrets.py on every deploy, so a value only
written into Secret Manager by hand is overwritten on the next release and the
surface silently reports "not configured". These tests pin both halves of the
path: the generator emits the key, and the runtime maps it onto the env var the
service reads.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import pytest

from hushh_mcp import runtime_settings
from hushh_mcp.services import advisor_directory_service as ads

_SYNC_SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "ops" / "sync_backend_runtime_secrets.py"
)

_CONFIG_ARGS = (
    "environment project db_host db_port db_name db_unix_socket "
    "cloudsql_instance_connection_name consent_sse_enabled sync_remote_enabled "
    "developer_api_enabled remote_mcp_enabled cors_allowed_origins "
    "obs_data_stale_ratio_threshold passkey_allowed_rp_ids plaid_env "
    "plaid_client_name plaid_country_codes plaid_webhook_url plaid_redirect_path "
    "plaid_redirect_uri plaid_tx_history_days one_location_read_only_state_enabled "
    "consent_center_summary_v2_enabled db_bulk_batching_enabled "
    "hushh_trusted_device_enabled hushh_trusted_device_uat_allowlist "
    "advisors_api_base_url"
).split()


def _load_sync_module():
    spec = importlib.util.spec_from_file_location("sync_backend_runtime_secrets", _SYNC_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _namespace(**overrides) -> argparse.Namespace:
    values = dict.fromkeys(_CONFIG_ARGS, "")
    values.update({"environment": "uat", "project": "hushh-pda-uat"})
    values.update(overrides)
    return argparse.Namespace(**values)


def test_generated_runtime_config_carries_the_advisors_base_url():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(
        _namespace(advisors_api_base_url="https://advisors.example")
    )
    assert config["advisors_api_base_url"] == "https://advisors.example"


def test_a_blank_base_url_is_omitted_so_unconfigured_lanes_stay_inert():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(_namespace(advisors_api_base_url=""))
    assert "advisors_api_base_url" not in config


def test_runtime_config_hydrates_the_env_var_the_service_reads(monkeypatch):
    monkeypatch.delenv("ADVISORS_API_BASE_URL", raising=False)
    monkeypatch.delenv("ADVISORS_API_BASE", raising=False)
    monkeypatch.setenv(
        "BACKEND_RUNTIME_CONFIG_JSON",
        json.dumps({"advisors_api_base_url": "https://advisors.example"}),
    )

    runtime_settings.hydrate_runtime_environment()

    assert ads.base_url() == "https://advisors.example"


def test_the_service_reports_unavailable_without_a_key(monkeypatch):
    monkeypatch.setenv("ADVISORS_API_BASE_URL", "https://advisors.example")
    monkeypatch.delenv("ADVISORS_API_KEY", raising=False)

    assert ads.is_configured() is False


def test_the_deploy_workflows_pass_the_flag_they_configure():
    """A generator argument nobody passes is the same as no argument at all."""
    workflow = (
        Path(__file__).resolve().parents[2] / ".github" / "workflows" / "deploy-uat.yml"
    ).read_text()
    assert "--advisors-api-base-url" in workflow


@pytest.mark.parametrize("key", ["advisors_api_base_url"])
def test_runtime_env_map_owns_the_key(key):
    assert runtime_settings._BACKEND_RUNTIME_ENV_MAP[key] == "ADVISORS_API_BASE_URL"
