"""The NWS Nearby base URL and key must survive a deploy in every lane.

BACKEND_RUNTIME_CONFIG_JSON is regenerated by
scripts/ops/sync_backend_runtime_secrets.py on every deploy, so a value written
into Secret Manager by hand is overwritten on the next release and the surface
silently reports "not configured".

This service differs from the two Connect directories in one way that these
tests exist to protect. There is exactly one deployed NWS service and every lane
calls it, so its base URL carries a real default rather than "". The advisor
directory's flag is passed only in deploy-uat.yml; copying that shape here would
have left production silently unconfigured while UAT looked healthy.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
from pathlib import Path

from hushh_mcp import runtime_settings
from hushh_mcp.services import nws_nearby_service as nws

_REPO_ROOT = Path(__file__).resolve().parents[2]
_SYNC_SCRIPT = _REPO_ROOT / "scripts" / "ops" / "sync_backend_runtime_secrets.py"

_CONFIG_ARGS = (
    "environment project db_host db_port db_name db_unix_socket "
    "cloudsql_instance_connection_name consent_sse_enabled sync_remote_enabled "
    "developer_api_enabled remote_mcp_enabled cors_allowed_origins "
    "obs_data_stale_ratio_threshold passkey_allowed_rp_ids plaid_env "
    "plaid_client_name plaid_country_codes plaid_webhook_url plaid_redirect_path "
    "plaid_redirect_uri plaid_tx_history_days one_location_read_only_state_enabled "
    "one_location_nearby_presence_mode one_location_nearby_presence_cohort "
    "consent_center_summary_v2_enabled db_bulk_batching_enabled "
    "hushh_trusted_device_enabled hushh_trusted_device_uat_allowlist "
    "advisors_api_base_url advisors_api_key_source_project "
    "advisors_api_key_source_secret insurance_agents_api_base_url "
    "insurance_agents_api_key_source_project insurance_agents_api_key_source_secret "
    "one_places_directory_enabled nws_nearby_api_base_url "
    "nws_nearby_api_key_source_project nws_nearby_api_key_source_secret "
    "nws_nearby_v4_api_base_url nws_nearby_v4_api_key_source_project "
    "nws_nearby_v4_api_key_source_secret"
).split()


def _load_sync_module():
    spec = importlib.util.spec_from_file_location("sync_backend_runtime_secrets", _SYNC_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _namespace(**overrides) -> argparse.Namespace:
    values = dict.fromkeys(_CONFIG_ARGS, "")
    values.update({"environment": "uat", "project": "hushh-pda-uat"})
    values.update(overrides)
    return argparse.Namespace(**values)


def test_generated_runtime_config_carries_the_nws_base_url():
    module = _load_sync_module()
    config = module._build_backend_runtime_config(
        _namespace(nws_nearby_api_base_url="https://nws.example")
    )
    assert config["nws_nearby_api_base_url"] == "https://nws.example"


def test_runtime_config_hydrates_the_env_var_the_service_reads(monkeypatch):
    monkeypatch.delenv("NWS_NEARBY_API_BASE_URL", raising=False)
    monkeypatch.setenv(
        "BACKEND_RUNTIME_CONFIG_JSON",
        json.dumps({"nws_nearby_api_base_url": "https://nws.example"}),
    )

    runtime_settings.hydrate_runtime_environment()

    assert nws.base_url() == "https://nws.example"


def test_runtime_env_map_owns_the_key():
    assert (
        runtime_settings._BACKEND_RUNTIME_ENV_MAP["nws_nearby_api_base_url"]
        == "NWS_NEARBY_API_BASE_URL"
    )


def test_the_service_reports_unavailable_without_a_key(monkeypatch):
    monkeypatch.setenv("NWS_NEARBY_API_BASE_URL", "https://nws.example")
    monkeypatch.delenv("NWS_NEARBY_API_KEY", raising=False)

    assert nws.is_configured() is False


def test_the_base_url_defaults_to_a_real_service_in_every_lane():
    """The one deployed NWS service is shared, so no lane may default to blank.

    Deploying one lane is half a release: a blank default plus a flag passed in
    only one workflow is exactly how a surface ends up working in UAT and inert
    in production, with nothing failing to say so. The advisor directory has
    precisely that shape, which is why this is asserted rather than assumed.
    """
    defaults = _sync_argument_defaults()

    base_url = defaults["nws-nearby-api-base-url"]
    assert base_url, "a blank default would leave any lane that omits the flag inert"
    assert base_url.startswith("https://")

    # The mirror source must be defaulted too, or a lane that omits the flag
    # copies nothing and the key never lands.
    assert defaults["nws-nearby-api-key-source-project"] == "hushh-tech-prod"
    assert defaults["nws-nearby-api-key-source-secret"] == "nws-nearby-api-key"


def _sync_argument_defaults() -> dict[str, str]:
    """Pull `--flag` defaults out of the generator's own add_argument calls.

    Read from source rather than by importing and driving argparse: main() has
    a dozen required arguments and does real work once they parse, so there is
    no seam that hands back a bare parser.
    """
    source = _SYNC_SCRIPT.read_text()
    pattern = re.compile(
        r"""add_argument\(\s*["']--(?P<flag>[a-z0-9-]+)["']\s*,\s*"""
        r"""default\s*=\s*["'](?P<default>[^"']*)["']""",
        re.VERBOSE,
    )
    found = {m.group("flag"): m.group("default") for m in pattern.finditer(source)}

    # The three NWS flags are declared across multiple lines by the formatter,
    # so fall back to a whitespace-tolerant search for any that did not match.
    multiline = re.compile(
        r"""add_argument\(\s*["']--(?P<flag>[a-z0-9-]+)["']\s*,\s*"""
        r"""default\s*=\s*["'](?P<default>[^"']*)["']\s*,?\s*\)""",
        re.VERBOSE | re.DOTALL,
    )
    for match in multiline.finditer(source):
        found.setdefault(match.group("flag"), match.group("default"))

    for flag in (
        "nws-nearby-api-base-url",
        "nws-nearby-api-key-source-project",
        "nws-nearby-api-key-source-secret",
    ):
        assert flag in found, f"{flag} is not declared with a default in the generator"
    return found


def test_the_key_is_mirrored_from_the_project_that_owns_it(monkeypatch):
    """NWS lives in hushh-tech-prod; every lane consumes it from there."""
    module = _load_sync_module()
    writes: list[tuple[str, str, str]] = []

    def fake_read(project: str, secret: str) -> str:
        if (project, secret) == ("hushh-tech-prod", "nws-nearby-api-key"):
            return "live-key"
        return "stale-key"

    monkeypatch.setattr(module, "_read_secret", fake_read)
    monkeypatch.setattr(module, "_upsert_secret", lambda p, s, v: writes.append((p, s, v)))

    status = module._mirror_directory_key(
        target_project="hushh-pda-uat",
        target_secret="NWS_NEARBY_API_KEY",  # noqa: S106
        source_project="hushh-tech-prod",
        # noqa comment: this is a secret *name*, not a credential value.
        source_secret="nws-nearby-api-key",  # noqa: S106
    )

    assert writes == [("hushh-pda-uat", "NWS_NEARBY_API_KEY", "live-key")]
    assert status and "rotated" in status


def test_the_deploy_step_mounts_the_key_into_the_backend():
    """A mirrored secret nothing mounts is a secret the runtime never sees."""
    # The deploy body lives in scripts/deploy/backend-deploy.sh (extracted for
    # Cloud Build's 10,000-char step-arg cap); this repo names the secret-binding
    # helper append_optional_secret. Read the whole deploy surface -- both files.
    cloudbuild = (
        (_REPO_ROOT / "deploy" / "backend.cloudbuild.yaml").read_text()
        + "\n"
        + (_REPO_ROOT / "scripts" / "deploy" / "backend-deploy.sh").read_text()
    )
    assert "append_optional_secret NWS_NEARBY_API_KEY NWS_NEARBY_API_KEY" in cloudbuild


def test_each_lane_mirrors_its_own_v4_credential() -> None:
    """A v4 key is bound upstream to one consumer and one project.

    The v2 key is a single shared service credential every lane may present.
    A v4 key is not: the upstream registry maps each key to exactly one
    consumer, so mirroring one into every lane would hand production UAT's
    identity and the upstream would refuse it as a project mismatch.
    """
    module = _load_sync_module()
    lanes = module._NWS_V4_KEY_SOURCE_BY_PROJECT

    assert lanes["hushh-pda-uat"] != lanes["hushh-pda"]
    assert len(set(lanes.values())) == len(lanes)
    # An unlisted lane mirrors nothing rather than borrowing another's key.
    assert lanes.get("hushh-pda-dev", "") == ""


def test_the_v4_project_id_is_the_lane_not_a_default() -> None:
    """A per-lane value carrying a default is how one lane inherits another."""
    module = _load_sync_module()

    uat = module._build_backend_runtime_config(_namespace(project="hushh-pda-uat"))
    prod = module._build_backend_runtime_config(_namespace(project="hushh-pda"))

    assert uat["nws_nearby_v4_project_id"] == "hushh-pda-uat"
    assert prod["nws_nearby_v4_project_id"] == "hushh-pda"
