-- Auto-generated SQLite schema mirroring live Postgres consent-path tables.
-- Generated by db/_gen_offline_schema.py against UAT Postgres. Do not hand-edit;
-- regenerate when migrations change consent/PKM/vault columns.

CREATE TABLE IF NOT EXISTS "consent_audit" (
  "id" INTEGER PRIMARY KEY,
  "token_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "agent_id" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "issued_at" INTEGER NOT NULL,
  "expires_at" INTEGER,
  "revoked_at" INTEGER,
  "metadata" TEXT,
  "token_type" TEXT,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "request_id" TEXT,
  "scope_description" TEXT,
  "poll_timeout_at" INTEGER
);

CREATE TABLE IF NOT EXISTS "consent_exports" (
  "consent_token" TEXT PRIMARY KEY,
  "user_id" TEXT,
  "encrypted_data" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "export_key" TEXT,
  "scope" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "created_at" TEXT,
  "wrapped_key_bundle" TEXT,
  "connector_key_id" TEXT,
  "connector_wrapping_alg" TEXT,
  "export_revision" INTEGER NOT NULL,
  "export_generated_at" TEXT,
  "source_content_revision" INTEGER,
  "source_manifest_revision" INTEGER,
  "refresh_status" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "consent_export_refresh_jobs" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "consent_token" TEXT NOT NULL,
  "granted_scope" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "trigger_domain" TEXT,
  "trigger_paths" TEXT NOT NULL,
  "requested_at" TEXT NOT NULL,
  "last_error" TEXT,
  "attempt_count" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "internal_access_events" (
  "id" INTEGER PRIMARY KEY,
  "token_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "agent_id" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "issued_at" INTEGER NOT NULL,
  "expires_at" INTEGER,
  "revoked_at" INTEGER,
  "metadata" TEXT,
  "token_type" TEXT,
  "request_id" TEXT,
  "scope_description" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_blobs" (
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "segment_id" TEXT NOT NULL,
  "ciphertext" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "algorithm" TEXT NOT NULL,
  "content_revision" INTEGER NOT NULL,
  "manifest_revision" INTEGER NOT NULL,
  "size_bytes" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY ("user_id", "domain", "segment_id")
);

CREATE TABLE IF NOT EXISTS "pkm_data" (
  "user_id" TEXT PRIMARY KEY,
  "encrypted_data_ciphertext" TEXT NOT NULL,
  "encrypted_data_iv" TEXT NOT NULL,
  "encrypted_data_tag" TEXT NOT NULL,
  "algorithm" TEXT,
  "data_version" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_index" (
  "user_id" TEXT PRIMARY KEY,
  "available_domains" TEXT NOT NULL,
  "domain_summaries" TEXT NOT NULL,
  "computed_tags" TEXT NOT NULL,
  "activity_score" REAL,
  "last_active_at" TEXT,
  "total_attributes" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "model_version" INTEGER NOT NULL,
  "last_upgraded_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_manifests" (
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "manifest_version" INTEGER NOT NULL,
  "structure_decision" TEXT NOT NULL,
  "summary_projection" TEXT NOT NULL,
  "top_level_scope_paths" TEXT NOT NULL,
  "externalizable_paths" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "path_count" INTEGER NOT NULL,
  "externalizable_path_count" INTEGER NOT NULL,
  "last_structured_at" TEXT NOT NULL,
  "last_content_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "domain_contract_version" INTEGER NOT NULL,
  "readable_summary_version" INTEGER NOT NULL,
  "upgraded_at" TEXT,
  "pkm_contract_version" TEXT NOT NULL,
  "readable_projection_version" TEXT NOT NULL,
  "latest_upgrade_commit_id" TEXT,
  PRIMARY KEY ("user_id", "domain")
);

CREATE TABLE IF NOT EXISTS "pkm_manifest_paths" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "json_path" TEXT NOT NULL,
  "parent_path" TEXT,
  "path_type" TEXT NOT NULL,
  "segment_id" TEXT NOT NULL,
  "scope_handle" TEXT,
  "exposure_eligibility" INTEGER NOT NULL,
  "consent_label" TEXT,
  "sensitivity_label" TEXT,
  "source_agent" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_events" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "operation_type" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "path_set" TEXT NOT NULL,
  "source_agent" TEXT,
  "confidence" REAL,
  "prior_manifest_version" INTEGER,
  "new_manifest_version" INTEGER,
  "metadata" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_scope_registry" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "scope_handle" TEXT NOT NULL,
  "scope_label" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "sensitivity_tier" TEXT NOT NULL,
  "scope_kind" TEXT NOT NULL,
  "exposure_enabled" INTEGER NOT NULL,
  "manifest_version" INTEGER NOT NULL,
  "summary_projection" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "visibility_posture" TEXT NOT NULL,
  "default_projection_ready" INTEGER NOT NULL,
  "default_projection_updated_at" TEXT,
  "owner_consent_override" INTEGER NOT NULL,
  "scope_origin" TEXT NOT NULL,
  "scope_origin_code" TEXT NOT NULL,
  "source_kind" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_default_available_projections" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "scope_handle" TEXT,
  "top_level_scope_path" TEXT NOT NULL,
  "projection_payload" TEXT NOT NULL,
  "projection_hash" TEXT NOT NULL,
  "projection_version" INTEGER NOT NULL,
  "manifest_version" INTEGER,
  "content_revision" INTEGER,
  "source_content_revision" INTEGER,
  "source_manifest_revision" INTEGER,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "revoked_at" TEXT,
  "revoked_reason" TEXT,
  "metadata" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_migration_state" (
  "user_id" TEXT PRIMARY KEY,
  "status" TEXT NOT NULL,
  "source_model" TEXT NOT NULL,
  "legacy_blob_present" INTEGER NOT NULL,
  "cutover_started_at" TEXT,
  "migrated_at" TEXT,
  "last_error" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_upgrade_runs" (
  "run_id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "from_model_version" INTEGER NOT NULL,
  "to_model_version" INTEGER NOT NULL,
  "current_domain" TEXT,
  "initiated_by" TEXT NOT NULL,
  "resume_count" INTEGER NOT NULL,
  "started_at" TEXT NOT NULL,
  "last_checkpoint_at" TEXT,
  "completed_at" TEXT,
  "last_error" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "mode" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_domain_revisions" (
  "revision_id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "source_content_revision" INTEGER NOT NULL,
  "source_manifest_revision" INTEGER NOT NULL,
  "is_origin" INTEGER NOT NULL,
  "archive_reason" TEXT NOT NULL,
  "source_commit_id" TEXT,
  "manifest_snapshot" TEXT NOT NULL,
  "path_rows_snapshot" TEXT NOT NULL,
  "scope_rows_snapshot" TEXT NOT NULL,
  "index_domain_summary_snapshot" TEXT NOT NULL,
  "index_domain_present" INTEGER NOT NULL,
  "retention_expires_at" TEXT,
  "restored_count" INTEGER NOT NULL,
  "last_restored_at" TEXT,
  "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_domain_revision_segments" (
  "revision_id" TEXT NOT NULL,
  "segment_id" TEXT NOT NULL,
  "ciphertext" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "algorithm" TEXT NOT NULL,
  "original_content_revision" INTEGER NOT NULL,
  "original_manifest_revision" INTEGER NOT NULL,
  "size_bytes" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY ("revision_id", "segment_id")
);

CREATE TABLE IF NOT EXISTS "pkm_domain_commits" (
  "commit_id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "commit_kind" TEXT NOT NULL,
  "request_fingerprint" TEXT,
  "run_id" TEXT,
  "claim_id" TEXT,
  "expected_content_revision" INTEGER NOT NULL,
  "expected_manifest_revision" INTEGER NOT NULL,
  "result_content_revision" INTEGER NOT NULL,
  "result_manifest_revision" INTEGER NOT NULL,
  "archived_revision_id" TEXT,
  "retention_expires_at" TEXT,
  "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_upgrade_claims" (
  "claim_id" TEXT PRIMARY KEY,
  "commit_id" TEXT NOT NULL,
  "run_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "source_content_revision" INTEGER NOT NULL,
  "source_manifest_revision" INTEGER NOT NULL,
  "target_domain_contract_version" INTEGER NOT NULL,
  "target_readable_summary_version" INTEGER NOT NULL,
  "target_pkm_contract_version" TEXT NOT NULL,
  "target_readable_projection_version" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "issued_at" TEXT NOT NULL,
  "committed_at" TEXT,
  "target_content_revision" INTEGER,
  "target_manifest_revision" INTEGER,
  "archived_revision_id" TEXT,
  "preservation_receipt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_upgrade_steps" (
  "id" INTEGER PRIMARY KEY,
  "run_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "from_domain_contract_version" INTEGER NOT NULL,
  "to_domain_contract_version" INTEGER NOT NULL,
  "from_readable_summary_version" INTEGER NOT NULL,
  "to_readable_summary_version" INTEGER NOT NULL,
  "attempt_count" INTEGER NOT NULL,
  "last_completed_content_revision" INTEGER,
  "last_completed_manifest_version" INTEGER,
  "checkpoint_payload" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "last_claim_id" TEXT,
  "last_commit_id" TEXT,
  "last_archived_revision_id" TEXT,
  "preservation_receipt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "vault_keys" (
  "user_id" TEXT PRIMARY KEY,
  "vault_status" TEXT NOT NULL,
  "vault_key_hash" TEXT,
  "primary_method" TEXT NOT NULL,
  "primary_wrapper_id" TEXT NOT NULL,
  "recovery_encrypted_vault_key" TEXT,
  "recovery_salt" TEXT,
  "recovery_iv" TEXT,
  "first_login_at" INTEGER,
  "last_login_at" INTEGER,
  "login_count" INTEGER NOT NULL,
  "setup_completed" INTEGER,
  "setup_skipped" INTEGER,
  "setup_completed_at" INTEGER,
  "nav_setup_completed_at" INTEGER,
  "nav_setup_skipped_at" INTEGER,
  "setup_capability_ids" TEXT,
  "setup_capabilities_updated_at" INTEGER,
  "setup_state_updated_at" INTEGER,
  "onboarding_journey_version" INTEGER,
  "onboarding_phase" TEXT,
  "onboarding_active_capability" TEXT,
  "onboarding_resume_route" TEXT,
  "onboarding_callback_state" TEXT,
  "onboarding_journey_updated_at" INTEGER,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  "user_email" TEXT
);

CREATE TABLE IF NOT EXISTS "vault_key_wrappers" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "wrapper_id" TEXT NOT NULL,
  "encrypted_vault_key" TEXT NOT NULL,
  "salt" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "passkey_credential_id" TEXT,
  "passkey_prf_salt" TEXT,
  "passkey_rp_id" TEXT,
  "passkey_provider" TEXT,
  "passkey_device_label" TEXT,
  "passkey_last_used_at" INTEGER,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_push_tokens" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "platform" TEXT NOT NULL,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "runtime_persona_state" (
  "user_id" TEXT PRIMARY KEY,
  "last_active_persona" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "user_email" TEXT
);

CREATE TABLE IF NOT EXISTS "developer_applications" (
  "id" INTEGER PRIMARY KEY,
  "slug" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "contact_name" TEXT,
  "contact_email" TEXT NOT NULL,
  "support_url" TEXT,
  "policy_url" TEXT,
  "website_url" TEXT,
  "use_case" TEXT,
  "requested_tool_groups" TEXT NOT NULL,
  "requested_agent_id" TEXT,
  "status" TEXT NOT NULL,
  "notes" TEXT,
  "reviewed_at" INTEGER,
  "reviewed_by" TEXT,
  "rejection_reason" TEXT,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "developer_apps" (
  "app_id" TEXT PRIMARY KEY,
  "application_id" INTEGER,
  "agent_id" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "contact_email" TEXT NOT NULL,
  "support_url" TEXT,
  "policy_url" TEXT,
  "website_url" TEXT,
  "status" TEXT NOT NULL,
  "allowed_tool_groups" TEXT NOT NULL,
  "approved_at" INTEGER,
  "approved_by" TEXT,
  "notes" TEXT,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  "owner_firebase_uid" TEXT,
  "owner_email" TEXT,
  "owner_display_name" TEXT,
  "owner_provider_ids" TEXT NOT NULL,
  "brand_image_url" TEXT,
  "kind" TEXT NOT NULL DEFAULT 'self_serve',
  "crm_id" TEXT,
  "allowed_capabilities" TEXT NOT NULL DEFAULT '[]',
  "schema_profile" TEXT NOT NULL DEFAULT 'standard',
  "oauth_client_credentials_enabled" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "developer_connector_keys" (
  "app_id" TEXT NOT NULL,
  "connector_key_id" TEXT NOT NULL,
  "connector_public_key" TEXT NOT NULL,
  "recipient_key_fingerprint" TEXT NOT NULL,
  "connector_wrapping_alg" TEXT NOT NULL DEFAULT 'X25519-AES256-GCM',
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" INTEGER NOT NULL,
  "retired_at" INTEGER,
  "revoked_at" INTEGER,
  PRIMARY KEY ("app_id", "connector_key_id")
);

CREATE TABLE IF NOT EXISTS "developer_tokens" (
  "id" INTEGER PRIMARY KEY,
  "app_id" TEXT NOT NULL,
  "token_prefix" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL,
  "label" TEXT,
  "created_by" TEXT,
  "revoked_by" TEXT,
  "created_at" INTEGER NOT NULL,
  "revoked_at" INTEGER,
  "last_used_at" INTEGER,
  "last_used_ip" TEXT,
  "last_used_user_agent" TEXT
);

-- WARNING: table users not found in live schema, skipped
