#!/usr/bin/env python3
"""Fail-closed Cloud Run to Cloud SQL connection admission check.

This command is read only. Run before a release with --environment uat or
--environment production. Its candidate allowance covers one new revision of
each configured database-using service during deployment overlap.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


DEFAULT_PROFILE = Path(__file__).resolve().parents[2] / "config/runtime-capacity.json"
POOL_KEYS = (
    "DB_POOL_MAX_SIZE",
    "DB_SQLALCHEMY_POOL_SIZE",
    "DB_SQLALCHEMY_MAX_OVERFLOW",
)


class BudgetError(ValueError):
    """Inventory or policy is incomplete, so admission cannot be proved."""


def positive_int(value: Any, label: str, *, zero_ok: bool = False) -> int:
    if isinstance(value, bool) or not str(value).isdigit():
        raise BudgetError(f"{label}: expected a non-negative integer, got {value!r}")
    number = int(value)
    if not zero_ok and number == 0:
        raise BudgetError(f"{label}: expected a positive integer")
    return number


def gcloud_json(*args: str) -> Any:
    command = ["gcloud", *args, "--format=json"]
    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
        return json.loads(result.stdout)
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        detail = (
            exc.stderr.strip()
            if isinstance(exc, subprocess.CalledProcessError)
            else str(exc)
        )
        raise BudgetError(
            f"Cloud inventory unavailable ({' '.join(command[:4])}): {detail}"
        ) from exc


def named_container(spec: dict[str, Any], name: str, label: str) -> dict[str, Any]:
    containers = spec.get("containers")
    if not isinstance(containers, list):
        raise BudgetError(f"{label}: container list unavailable")
    matches = [item for item in containers if item.get("name") == name]
    if len(matches) == 1:
        return matches[0]
    # Older Cloud Run revisions were deployed with an autogenerated container
    # name (for example consent-protocol-1). A single container is unambiguous.
    if not matches and len(containers) == 1:
        return containers[0]
    raise BudgetError(f"{label}: expected exactly one application container")


def env_values(container: dict[str, Any], label: str) -> dict[str, str]:
    env = container.get("env")
    if not isinstance(env, list):
        raise BudgetError(f"{label}: environment unavailable")
    result: dict[str, str] = {}
    for item in env:
        name = item.get("name")
        if name in result:
            raise BudgetError(f"{label}: duplicate {name}")
        if isinstance(name, str) and "value" in item:
            result[name] = str(item["value"])
    return result


def revision_connections(
    revision: dict[str, Any],
    service: str,
    settings: dict[str, Any],
    database_connection_name: str,
) -> dict[str, Any]:
    metadata = revision.get("metadata") or {}
    name = metadata.get("name")
    if not isinstance(name, str) or not name.startswith(f"{service}-"):
        raise BudgetError(f"{service}: revision name missing or mismatched")
    annotations = metadata.get("annotations") or {}
    cloudsql = annotations.get("run.googleapis.com/cloudsql-instances", "")
    if database_connection_name not in cloudsql.split(","):
        raise BudgetError(
            f"{name}: expected Cloud SQL attachment {database_connection_name}"
        )
    maximum = positive_int(
        annotations.get("autoscaling.knative.dev/maxScale"),
        f"{name} revision max instances",
    )
    spec = revision.get("spec") or {}
    container = named_container(spec, settings["container"], name)
    env = env_values(container, name)
    pools = [
        positive_int(
            env.get(key), f"{name} {key}", zero_ok=(key == "DB_SQLALCHEMY_MAX_OVERFLOW")
        )
        for key in POOL_KEYS
    ]
    workers = positive_int(settings["workers_per_instance"], f"{service} workers")
    # Drive workers specify -w in the revision command; check that the profile
    # cannot silently undercount a changed command line.
    args = container.get("args") or []
    if "-w" in args:
        index = args.index("-w")
        if index + 1 >= len(args):
            raise BudgetError(f"{name}: malformed worker count")
        workers = positive_int(args[index + 1], f"{name} workers")
    elif "--workers" in args:
        index = args.index("--workers")
        if index + 1 >= len(args):
            raise BudgetError(f"{name}: malformed worker count")
        workers = positive_int(args[index + 1], f"{name} workers")
    return {
        "name": name,
        "max_instances": maximum,
        "workers_per_instance": workers,
        "connections_per_worker": sum(pools),
        "connections": maximum * workers * sum(pools),
    }


def candidate_connections(service: str, settings: dict[str, Any]) -> dict[str, Any]:
    candidate = settings["candidate"]
    maximum = positive_int(
        candidate["max_instances"], f"{service} candidate max instances"
    )
    workers = positive_int(
        candidate["workers_per_instance"], f"{service} candidate workers"
    )
    pools = [
        positive_int(
            candidate[key],
            f"{service} candidate {key}",
            zero_ok=(key == "sqlalchemy_max_overflow"),
        )
        for key in (
            "asyncpg_pool_max",
            "sqlalchemy_pool_size",
            "sqlalchemy_max_overflow",
        )
    ]
    return {
        "name": f"{service}:new-candidate",
        "max_instances": maximum,
        "workers_per_instance": workers,
        "connections_per_worker": sum(pools),
        "connections": maximum * workers * sum(pools),
    }


def service_budget(
    service: str,
    settings: dict[str, Any],
    service_doc: dict[str, Any],
    revisions: list[dict[str, Any]],
    database_connection_name: str,
) -> list[dict[str, Any]]:
    traffic = (service_doc.get("status") or {}).get("traffic")
    if not isinstance(traffic, list) or not traffic:
        raise BudgetError(f"{service}: service traffic unavailable")
    referenced: set[str] = set()
    for target in traffic:
        revision = target.get("revisionName")
        if not isinstance(revision, str):
            raise BudgetError(f"{service}: traffic target has no revision name")
        percent = target.get("percent", 0)
        if positive_int(
            percent, f"{service} traffic percent", zero_ok=True
        ) > 0 or target.get("tag"):
            referenced.add(revision)
    if not referenced:
        raise BudgetError(f"{service}: no serving or tagged revision")
    status = service_doc.get("status") or {}
    latest = status.get("latestReadyRevisionName")
    if latest:
        referenced.add(latest)  # in-flight or just-created candidate
    by_name = {(rev.get("metadata") or {}).get("name"): rev for rev in revisions}
    missing = referenced - by_name.keys()
    if missing:
        raise BudgetError(
            f"{service}: referenced revisions missing from inventory: {sorted(missing)}"
        )
    # Keep the newest unreferenced revision as the rollback allowance. A tagged
    # rollback is already in referenced and is not counted twice.
    unreferenced = [
        rev
        for rev in revisions
        if (rev.get("metadata") or {}).get("name") not in referenced
    ]
    if unreferenced:
        rollback = max(
            unreferenced,
            key=lambda rev: (rev.get("metadata") or {}).get("creationTimestamp", ""),
        )
        referenced.add(rollback["metadata"]["name"])
    return [
        revision_connections(by_name[name], service, settings, database_connection_name)
        for name in sorted(referenced)
    ]


def job_budget(
    job: dict[str, Any], settings: dict[str, Any], database_connection_name: str
) -> dict[str, Any]:
    name = (job.get("metadata") or {}).get("name")
    spec = ((job.get("spec") or {}).get("template") or {}).get("spec") or {}
    annotations = (
        ((job.get("spec") or {}).get("template") or {})
        .get("metadata", {})
        .get("annotations", {})
    )
    task = (spec.get("template") or {}).get("spec") or {}
    task_count = positive_int(spec.get("taskCount"), f"{name} task count")
    # The API omits parallelism when it uses the default. Task count is the
    # conservative ceiling, regardless of which default Cloud Run applies.
    parallelism = positive_int(
        spec.get("parallelism", task_count), f"{name} parallelism"
    )
    configured = positive_int(
        settings["connections_per_task"], f"{name} connections per task"
    )
    executions = positive_int(
        settings["concurrent_executions"], f"{name} concurrent executions"
    )
    attached = database_connection_name in annotations.get(
        "run.googleapis.com/cloudsql-instances", ""
    ).split(",")
    containers = task.get("containers") or []
    if not isinstance(containers, list) or not containers:
        raise BudgetError(f"{name}: task containers unavailable")
    live_pool = 0
    for container in containers:
        env = env_values(container, name)
        present = [key in env for key in POOL_KEYS]
        if any(present) and not all(present):
            raise BudgetError(f"{name}: partial DB pool settings")
        if all(present):
            live_pool += sum(
                positive_int(
                    env[key],
                    f"{name} {key}",
                    zero_ok=(key == "DB_SQLALCHEMY_MAX_OVERFLOW"),
                )
                for key in POOL_KEYS
            )
    if not attached and live_pool:
        raise BudgetError(
            f"{name}: DB pools configured without expected Cloud SQL attachment"
        )
    per_task = max(configured, live_pool) if attached else configured
    connections = min(parallelism, task_count) * executions * per_task
    return {
        "name": name,
        "parallel_tasks": min(parallelism, task_count),
        "concurrent_executions": executions,
        "connections_per_task": per_task,
        "cloudsql_attached": attached,
        "connections": connections,
    }


def evaluate(
    profile: dict[str, Any], environment: str, inventory: dict[str, Any]
) -> dict[str, Any]:
    if profile.get("schema_version") != 1:
        raise BudgetError("unsupported capacity profile version")
    config = profile["environments"][environment]
    maximum = positive_int(
        profile["database_max_connections"], "database max connections"
    )
    limit = positive_int(profile["admission_limit"], "admission limit")
    reserve = positive_int(profile["administrative_reserve"], "administrative reserve")
    if limit > maximum or reserve >= limit:
        raise BudgetError("invalid database connection policy")
    live_maximum = inventory["database_max_connections"]
    if live_maximum != maximum:
        raise BudgetError(
            f"Cloud SQL max_connections is {live_maximum}; profile requires {maximum}"
        )
    connection_name = (
        f"{config['project']}:{profile['region']}:{config['database_instance']}"
    )
    service_rows: list[dict[str, Any]] = []
    expected_services = set(config["services"])
    optional_services = {
        name
        for name, settings in config["services"].items()
        if settings.get("optional_existing")
    }
    if (
        not expected_services - optional_services <= set(inventory["services"])
        or set(inventory["services"]) - expected_services
    ):
        raise BudgetError("service inventory differs from capacity profile")
    for name, settings in config["services"].items():
        if name in inventory["services"]:
            service = inventory["services"][name]
            service_rows.extend(
                service_budget(
                    name,
                    settings,
                    service["service"],
                    service["revisions"],
                    connection_name,
                )
            )
        service_rows.append(candidate_connections(name, settings))
    if set(inventory["jobs"]) != set(config["jobs"]):
        extra = set(inventory["jobs"]) - set(config["jobs"])
        missing = set(config["jobs"]) - set(inventory["jobs"])
        raise BudgetError(
            f"job inventory drift: unprofiled={sorted(extra)}, missing={sorted(missing)}"
        )
    job_rows = [
        job_budget(inventory["jobs"][name], settings, connection_name)
        for name, settings in config["jobs"].items()
    ]
    projected = reserve + sum(row["connections"] for row in service_rows + job_rows)
    return {
        "environment": environment,
        "project": config["project"],
        "database": connection_name,
        "verified_max_connections": live_maximum,
        "admission_limit": limit,
        "administrative_reserve": reserve,
        "services": service_rows,
        "jobs": job_rows,
        "projected_connections": projected,
        "headroom_to_limit": limit - projected,
        "admitted": projected <= limit,
    }


def collect(profile: dict[str, Any], environment: str) -> dict[str, Any]:
    config = profile["environments"][environment]
    project, region = config["project"], profile["region"]
    sql = gcloud_json(
        "sql",
        "instances",
        "describe",
        config["database_instance"],
        f"--project={project}",
    )
    if sql.get("state") != "RUNNABLE":
        raise BudgetError(f"Cloud SQL instance is not RUNNABLE: {sql.get('state')}")
    flags = (sql.get("settings") or {}).get("databaseFlags") or []
    if not any(
        flag.get("name") == "cloudsql.iam_authentication" and flag.get("value") == "on"
        for flag in flags
    ):
        raise BudgetError("Cloud SQL IAM authentication flag is not on")
    values = [
        flag.get("value") for flag in flags if flag.get("name") == "max_connections"
    ]
    if len(values) != 1:
        raise BudgetError(
            "Cloud SQL max_connections must be explicitly configured and readable"
        )
    maximum = positive_int(values[0], "Cloud SQL max_connections")
    opts = (f"--project={project}", f"--region={region}")
    listed_services = gcloud_json("run", "services", "list", *opts)
    if not isinstance(listed_services, list):
        raise BudgetError("Cloud Run services inventory unavailable")
    service_names = {
        (service.get("metadata") or {}).get("name") for service in listed_services
    }
    profiled = set(config["services"])
    non_database = set(config["non_database_services"])
    if None in service_names:
        raise BudgetError("Cloud Run service inventory contains an unnamed service")
    if service_names - profiled != non_database:
        raise BudgetError(
            f"Cloud Run service inventory drift: unprofiled={sorted((service_names - profiled) - non_database)}, "
            f"missing declared non-DB={sorted(non_database - service_names)}"
        )
    required = {
        name
        for name, settings in config["services"].items()
        if not settings.get("optional_existing")
    }
    if required - service_names:
        raise BudgetError(
            f"required database services missing: {sorted(required - service_names)}"
        )
    services: dict[str, Any] = {}
    for name in service_names:
        opts = (f"--project={project}", f"--region={region}")
        service = gcloud_json("run", "services", "describe", name, *opts)
        revisions = gcloud_json("run", "revisions", "list", f"--service={name}", *opts)
        if not isinstance(revisions, list):
            raise BudgetError(f"{name}: revision inventory unavailable")
        if name in non_database:
            connection_name = f"{project}:{region}:{config['database_instance']}"
            traffic = (service.get("status") or {}).get("traffic")
            if not isinstance(traffic, list):
                raise BudgetError(f"{name}: traffic unavailable")
            referenced = {
                target.get("revisionName")
                for target in traffic
                if target.get("tag") or target.get("percent", 0)
            }
            latest = (service.get("status") or {}).get("latestReadyRevisionName")
            if latest:
                referenced.add(latest)
            by_name = {
                (rev.get("metadata") or {}).get("name"): rev for rev in revisions
            }
            if None in referenced or referenced - by_name.keys():
                raise BudgetError(f"{name}: referenced revision unavailable")
            for revision in (by_name[revision_name] for revision_name in referenced):
                annotations = (revision.get("metadata") or {}).get("annotations") or {}
                if connection_name in annotations.get(
                    "run.googleapis.com/cloudsql-instances", ""
                ).split(","):
                    raise BudgetError(
                        f"{name}: reachable revision attaches to budgeted Cloud SQL"
                    )
        else:
            services[name] = {"service": service, "revisions": revisions}
    listed = gcloud_json("run", "jobs", "list", *opts)
    if not isinstance(listed, list):
        raise BudgetError("Cloud Run jobs inventory unavailable")
    names = [(job.get("metadata") or {}).get("name") for job in listed]
    if any(not isinstance(name, str) for name in names) or len(names) != len(
        set(names)
    ):
        raise BudgetError("Cloud Run jobs inventory malformed")
    jobs = {name: gcloud_json("run", "jobs", "describe", name, *opts) for name in names}
    return {"database_max_connections": maximum, "services": services, "jobs": jobs}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment", choices=("uat", "production"), required=True)
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument(
        "--report-only",
        action="store_true",
        help="Report an over-budget result without a nonzero exit",
    )
    parser.add_argument("--output", choices=("text", "json"), default="text")
    args = parser.parse_args()
    try:
        profile = json.loads(args.profile.read_text())
        report = evaluate(profile, args.environment, collect(profile, args.environment))
    except (OSError, KeyError, TypeError, json.JSONDecodeError, BudgetError) as exc:
        print(f"capacity budget blocked: {exc}", file=sys.stderr)
        return 2
    if args.output == "json":
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(
            f"{args.environment}: projected {report['projected_connections']} / {report['admission_limit']} "
            f"(Cloud SQL max {report['verified_max_connections']}, admin reserve {report['administrative_reserve']})"
        )
        for row in report["services"] + report["jobs"]:
            print(f"  {row['name']}: {row['connections']}")
        print("ADMIT" if report["admitted"] else "BLOCK: connection budget exceeded")
    return 0 if report["admitted"] or args.report_only else 1


if __name__ == "__main__":
    raise SystemExit(main())
