// @vitest-environment node
//
// Runs in the `node` environment (not jsdom): the crypto path is pure Web Crypto
// and jsdom hands out cross-realm ArrayBuffers that Node's SubtleCrypto rejects
// via strict instanceof. Node provides globalThis.crypto (subtle) natively.
import { describe, expect, it } from "vitest";
import { decryptLocationEnvelopeWithKey } from "@/lib/one-location/encryption";
import type { OneLocationEncryptedEnvelope } from "@/lib/one-location/types";

// Recipient private key matching the fixture public key in the Swift test.
const privateKeyJwk = {
  kty: "EC",
  crv: "P-256",
  x: "bYSlqg5_E4ruu5r3PRtBxjAM4a_DqCJwaLIXYu2Sats",
  y: "uLLY49pNxir21iuk3Wy0N852NvxZYTGFtEUotBQ8ZNM",
  d: "0QSES3IFfQY4dKAIft3Kz5aVbxxIGWuiCd84LdYBjcs",
  key_ops: ["deriveKey"],
  ext: true,
};

// Generated by AppTests/LocationEnvelopeCryptoTests.testPrintGoldenEnvelopeForJS
// (native CryptoKit ECIES). Proves the Swift output decrypts with the production
// JS crypto path — the byte-exact parity guarantee.
const swiftEnvelope = {
  algorithm: "ECDH-P256-AES256-GCM",
  capturedAt: "2026-07-09T00:00:00.000Z",
  ciphertext:
    "yxJyxC-p2ynGitYgLAeHYx8R52f_Eg3UtH4T_4uqqPEQtWHxyrqzQW8mVZcWWiMp5H4NaBWHPHaTR0lfY90CJY9K4AI_u6x5c97Hk3RTb5L6ikPDu-nO7iuYvPIJ8gEbgFHBJEzCIbsIWNI6FW9OLFH9B9O6v0M",
  iv: "xlME_9WW-Zj_Q5Vo",
  metadata: { payload: "coordinate_envelope", plaintext: false },
  recipientKeyId: "k1",
  senderEphemeralPublicKeyJwk: {
    crv: "P-256",
    kty: "EC",
    x: "oU87zFooXYyThlmiHwhMGijg7S3yuw3r1Z4a0R3qI98",
    y: "JeP07aD3vTzwqGtNtI4iaz4uqmKNyGE2A7y84-Ocm8g",
  },
  sourcePlatform: "ios",
} as unknown as OneLocationEncryptedEnvelope;

describe("Swift → JS envelope parity", () => {
  it("decrypts a natively-produced envelope to the original point", async () => {
    const point = await decryptLocationEnvelopeWithKey({
      privateKeyJwk,
      envelope: swiftEnvelope,
    });
    expect(point.latitude).toBeCloseTo(12.9716, 4);
    expect(point.longitude).toBeCloseTo(77.5946, 4);
    expect(point.sourcePlatform).toBe("ios");
  });
});
