/*
 * SPDX-FileCopyrightText: 2026 Hushh
 * SPDX-License-Identifier: Apache-2.0
 */
package ai.hussh.consent;

import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.crypto.AEADBadTagException;

/** Dependency-free executable test against a vector generated by the Python reference code. */
public final class ConsentExportDecryptorSelfTest {
  private static final String CONNECTOR_PRIVATE_PKCS8 =
      "MC4CAQAwBQYDK2VuBCIEIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f";
  private static final String EXPECTED_PLAINTEXT =
      "{\"financial\":{\"portfolio\":{\"account_info\":{\"brokerage\":\"Demo Brokerage\"},"
          + "\"holdings\":[{\"quantity\":12.5,\"symbol\":\"AAPL\"},"
          + "{\"quantity\":4,\"symbol\":\"MSFT\"}]}}}";

  private ConsentExportDecryptorSelfTest() {}

  public static void main(String[] args) throws Exception {
    PrivateKey connectorPrivateKey =
        ConsentExportDecryptor.x25519PrivateKeyFromPkcs8(
            Base64.getDecoder().decode(CONNECTOR_PRIVATE_PKCS8));
    ConsentExportDecryptor.ExpectedContext expected =
        new ConsentExportDecryptor.ExpectedContext(
            "app_partner_crm_uat",
            "grant_java_vector_001",
            7,
            "attr.financial.portfolio.*",
            "attr.financial.portfolio.*",
            "scope_java_vector_001",
            "sha256:eedd883da0a9451593dc0a38e583fb770fa27dbbed209c20404e075e68c4f0c9",
            1798761600000L,
            "partner-crm-key-2026-07");

    ConsentExportDecryptor.FlatExportPackage export = vectorExport();
    String plaintext =
        new String(
            ConsentExportDecryptor.decryptAt(
                export, connectorPrivateKey, expected, 1780000000000L),
            StandardCharsets.UTF_8);
    assertEquals(EXPECTED_PLAINTEXT, plaintext, "cross-language plaintext");

    ConsentExportDecryptor.FlatExportPackage tampered =
        new ConsentExportDecryptor.FlatExportPackage(
            export.status(),
            export.delivery(),
            export.expectedScope(),
            export.grantedScope(),
            export.expiresAt(),
            export.exportRevision(),
            export.ciphertext(),
            export.payloadIv(),
            "GkaOGW4cpby64PcjP0H7uw==",
            export.wrappedExportKey(),
            export.wrappedKeyIv(),
            export.wrappedKeyTag(),
            export.senderPublicKey(),
            export.connectorKeyId(),
            export.wrappingAlg(),
            export.exportEnvelope());
    try {
      ConsentExportDecryptor.decryptAt(
          tampered, connectorPrivateKey, expected, 1780000000000L);
      throw new AssertionError("tampered payload tag was accepted");
    } catch (AEADBadTagException expectedFailure) {
      // Expected fail-closed behavior.
    }

    System.out.println("Java 17/JCA Hussh export decryptor: PASS");
  }

  private static ConsentExportDecryptor.FlatExportPackage vectorExport() {
    Map<String, Object> aad = new LinkedHashMap<>();
    aad.put("version", 2);
    aad.put("app_id", "app_partner_crm_uat");
    aad.put("grant_id", "grant_java_vector_001");
    aad.put("export_id", "0123456789abcdef0123456789abcdef");
    aad.put("revision", 7);
    aad.put("machine_scope", "attr.financial.portfolio.*");
    aad.put("scope_handle", "scope_java_vector_001");
    aad.put(
        "recipient_key_fingerprint",
        "sha256:eedd883da0a9451593dc0a38e583fb770fa27dbbed209c20404e075e68c4f0c9");
    aad.put("payload_algorithm", "AES-256-GCM");
    aad.put("expires_at_ms", 1798761600000L);

    Map<String, Object> envelope = new LinkedHashMap<>();
    envelope.put("version", 2);
    envelope.put("export_id", "0123456789abcdef0123456789abcdef");
    envelope.put("aad", aad);
    envelope.put(
        "aad_sha256",
        "sha256:da623bf92e29846c22a4a449dbf7b973d3ac0f95fbfc2cf074e3eb20415fc5d7");
    envelope.put(
        "ciphertext_sha256",
        "sha256:8d8e77ae971d8cdf8ba552ec9e76244694794f888150b687bc0928e93bf3d0c0");
    envelope.put("ciphertext_bytes", 153);

    return new ConsentExportDecryptor.FlatExportPackage(
        "success",
        "encrypted_inline",
        "attr.financial.portfolio.*",
        "attr.financial.portfolio.*",
        1798761600000L,
        7,
        "1wpvbGn1/sVg4BUUP/1+e2Bemnd4UvhhLECwmsqhZJRVgZlBEqW55orD2wp5XG9Bm1QMKxBkl5Yh"
            + "c3QE3MO+3y/E3S8oKn26biv1Ftd9JnX6IXTfM0m6yC8wMiCiPAd2HfVcy95/Uu9m4eZ2y3LtmL"
            + "NC9FUBw3sX3Raorx0HS90VNx5qz5UdFGFTefQx+QD1o2aZtHqrofiu",
        "YGFiY2RlZmdoaWpr",
        "GUaOGW4cpby64PcjP0H7uw==",
        "WYr+xGL1euHWDZIagXKVN5mS2CLLSDBV+ptd2yN3ML8=",
        "bG1ub3BxcnN0dXZ3",
        "itpinuxYZD1pTWZ0evRmrA==",
        "NYBy1jZYgNGu6jKa35EhODhR7SGijjt16WXQ0s0WYlQ=",
        "partner-crm-key-2026-07",
        "X25519-AES256-GCM",
        envelope);
  }

  private static void assertEquals(String expected, String actual, String label) {
    if (!expected.equals(actual)) {
      throw new AssertionError(label + " mismatch\nexpected: " + expected + "\nactual: " + actual);
    }
  }
}
