using System.Text.Json;
using System.Text.Json.Serialization;

namespace OneWindows.Consent.Tests;

public sealed class ScopeMatchCase
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("grantedScope")]
    public string GrantedScope { get; set; } = "";

    [JsonPropertyName("requestedScope")]
    public string RequestedScope { get; set; } = "";

    [JsonPropertyName("expectedMatches")]
    public bool ExpectedMatches { get; set; }

    public override string ToString() => Name;
}

/// <summary>
/// Parity tests generated by the real Python scope_matches() (see
/// scripts/generate_scope_golden_vectors.py) -- not hand-picked assumptions.
/// </summary>
public class ScopeMatcherGoldenVectorTests
{
    private static readonly Lazy<List<ScopeMatchCase>> _cases = new(LoadCases);

    private static List<ScopeMatchCase> LoadCases()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "fixtures", "scope_matches_golden_vectors.json");
        string json = File.ReadAllText(path);
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var doc = JsonSerializer.Deserialize<ScopeMatchFile>(json, options)
            ?? throw new InvalidOperationException($"Failed to deserialize {path}");
        return doc.Cases;
    }

    private sealed class ScopeMatchFile
    {
        [JsonPropertyName("cases")]
        public List<ScopeMatchCase> Cases { get; set; } = new();
    }

    public static IEnumerable<object[]> Cases() => _cases.Value.Select(c => new object[] { c });

    [Fact]
    public void FixtureLoads()
    {
        Assert.NotEmpty(_cases.Value);
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Matches_AgreesWithPython(ScopeMatchCase testCase)
    {
        bool actual = ScopeMatcher.Matches(testCase.GrantedScope, testCase.RequestedScope);
        Assert.Equal(testCase.ExpectedMatches, actual);
    }
}
