namespace OneWindows.Consent.Tests;

/// <summary>
/// Parity tests: every case here is generated by the real Python
/// hushh_mcp/consent/token.py (see scripts/generate_golden_vectors.py), not
/// invented in C#. A pass means this port produces byte-for-byte identical
/// tokens and signatures, and agrees on valid/invalid outcomes.
/// </summary>
public class TokenCodecGoldenVectorTests
{
    private static string SigningKey => GoldenVectorFixture.Data.SigningKey;

    public static IEnumerable<object[]> Cases() =>
        GoldenVectorFixture.Data.Cases.Select(c => new object[] { c });

    public static IEnumerable<object[]> MalformedCases() =>
        GoldenVectorFixture.Data.MalformedCases.Select(c => new object[] { c });

    public static IEnumerable<object[]> GateCases() =>
        GoldenVectorFixture.Data.GateCases.Select(c => new object[] { c });

    [Fact]
    public void FixtureLoads()
    {
        Assert.Equal("HCT", GoldenVectorFixture.Data.ConsentTokenPrefix);
        Assert.NotEmpty(GoldenVectorFixture.Data.Cases);
        Assert.NotEmpty(GoldenVectorFixture.Data.MalformedCases);
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Issue_MatchesPythonTokenAndSignature(GoldenCase testCase)
    {
        var (token, signature) = TokenCodec.Issue(
            testCase.Input.UserId,
            testCase.Input.AgentId,
            testCase.Input.Scope,
            testCase.Input.IssuedAt,
            testCase.Input.ExpiresAt,
            testCase.Input.Commercial,
            SigningKey);

        Assert.Equal(testCase.ExpectedToken, token);
        Assert.Equal(testCase.ExpectedSignature, signature);
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Validate_MatchesPythonOutcome(GoldenCase testCase)
    {
        var result = TokenCodec.Validate(testCase.ExpectedToken, SigningKey);

        Assert.Equal(testCase.ExpectedValid, result.IsValid);
        Assert.Equal(testCase.ExpectedReason, result.Reason);

        if (testCase.ExpectedValid)
        {
            Assert.NotNull(result.Token);
            Assert.Equal(testCase.Input.UserId, result.Token!.UserId);
            Assert.Equal(testCase.Input.AgentId, result.Token.AgentId);
            Assert.Equal(testCase.Input.Scope, result.Token.Scope);
            Assert.Equal(testCase.Input.IssuedAt, result.Token.IssuedAt);
            Assert.Equal(testCase.Input.ExpiresAt, result.Token.ExpiresAt);
            Assert.Equal(testCase.Input.Commercial, result.Token.Commercial);
            Assert.Equal(testCase.ExpectedSignature, result.Token.Signature);
        }
        else
        {
            Assert.Null(result.Token);
        }
    }

    [Theory]
    [MemberData(nameof(MalformedCases))]
    public void Validate_RejectsMalformedTokensLikePython(MalformedCase testCase)
    {
        var result = TokenCodec.Validate(testCase.RawToken, SigningKey);

        Assert.Equal(testCase.ExpectedValid, result.IsValid);
        Assert.Null(result.Token);
        Assert.NotNull(result.Reason);
        Assert.Contains(testCase.ExpectedReasonContains, result.Reason);
    }

    [Theory]
    [MemberData(nameof(GateCases))]
    public void Validate_ExpectedScopeAndCommercialGates_MatchPython(GateCase testCase)
    {
        var result = TokenCodec.Validate(testCase.Token, SigningKey, testCase.ExpectedScope, testCase.RequireCommercial);

        Assert.Equal(testCase.ExpectedValid, result.IsValid);
        Assert.Equal(testCase.ExpectedReason, result.Reason);
        Assert.Equal(testCase.ExpectedValid, result.Token is not null);
    }
}
