"""Focused tests for the transcript-first Location command boundary."""

from __future__ import annotations

import asyncio
import json
from base64 import b64encode
from contextlib import asynccontextmanager
from types import ModuleType, SimpleNamespace

import pytest

from hushh_mcp.services import location_command_runtime as location_command_module
from hushh_mcp.services.location_command_runtime import (
    DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL,
    LOCATION_COMMAND_PROTOCOL_VERSION,
    LocationCommandPlanV1,
    LocationCommandResultV1,
    LocationCommandRuntime,
    LocationCommandTurnGate,
    _safe_navigation_directive,
    location_command_runtime_enabled,
    location_command_transcribe_model_id,
)


class _StandaloneCommandRelayHarness:
    """Test seam that invokes the standalone command relay, never the chat route.

    The runtime tests were originally imported with a compatibility seam for
    the conversational relay.  Keep their realistic socket/provider fakes,
    but construct the standalone relay's explicit dependency bundle here so
    the tests exercise the command-only transport and cannot accidentally
    re-enable the chat route.
    """

    def __init__(self, module: ModuleType) -> None:
        self._module = module
        self.WebSocketDisconnect = module.WebSocketDisconnect
        self.get_location_command_runtime = location_command_module.get_location_command_runtime
        self._LOCATION_COMMAND_RESOLUTION_TIMEOUT_SECONDS = module._PLANNING_TIMEOUT_SECONDS

    def _build_location_command_live_config(self, genai_types: object) -> object:
        return self._module._location_command_live_config(genai_types)

    def _location_command_provider_setup_observed(self, session: object) -> bool:
        return self._module._provider_setup_observed(session)

    async def _run_location_command_relay(
        self,
        websocket: object,
        *,
        uid: str,
        client: object,
        model: str,
    ) -> None:
        dependencies = self._module._CommandRuntimeDependencies(
            runtime_factory=self.get_location_command_runtime,
            turn_gate_factory=LocationCommandTurnGate,
            runtime_enabled=lambda: True,
            transcribe_model=lambda: model,
            protocol_version=self._module.LOCATION_COMMAND_PROTOCOL_VERSION,
        )
        previous_timeout = self._module._PLANNING_TIMEOUT_SECONDS
        self._module._PLANNING_TIMEOUT_SECONDS = self._LOCATION_COMMAND_RESOLUTION_TIMEOUT_SECONDS
        try:
            await self._module._run_location_command_relay(
                websocket,  # type: ignore[arg-type]
                uid=uid,
                client=client,
                model=model,
                dependencies=dependencies,
            )
        finally:
            self._module._PLANNING_TIMEOUT_SECONDS = previous_timeout


def _location_command_relay_or_skip() -> _StandaloneCommandRelayHarness:
    """Return the standalone command-only relay under test."""

    try:
        from api.routes.one import location_command_relay
    except Exception as exc:  # noqa: BLE001 - production fails closed
        if exc.__class__.__name__ == "CapabilityGraphArtifactError":
            pytest.skip("Capability graph artifact is being regenerated by the graph lane.")
        raise
    return _StandaloneCommandRelayHarness(location_command_relay)


def _begin(turn_id: str = "turn_123") -> dict[str, object]:
    return {
        "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
        "turnId": turn_id,
        "startSequence": 1,
    }


def _end(
    turn_id: str = "turn_123", final_sequence: int = 1, *, cancelled: bool = False
) -> dict[str, object]:
    return {
        "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
        "turnId": turn_id,
        "finalSequence": final_sequence,
        "cancelled": cancelled,
    }


def test_final_transcript_and_provider_turn_complete_are_both_required_for_routing() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None
    assert turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    # Gemini's final text is transient and cannot route until Gemini also
    # reports the automatic speech-end/turnComplete boundary.
    assert gate.receive_final_transcript("do location onboarding") is None
    assert gate.take_resolution() is None
    assert gate.mark_provider_turn_complete() is True
    assert gate.take_resolution() == ("turn_123", "do location onboarding")
    assert gate.take_resolution() is None


def test_no_input_turn_or_pcm_is_accepted_before_provider_and_context_ready() -> None:
    gate = LocationCommandTurnGate()

    turn, error = gate.begin(_begin(), provider_ready=False, context_ready=True)
    assert turn is None
    assert error == "not_ready"
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) == "turn_not_started"

    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=False)
    assert turn is None
    assert error == "not_ready"


def test_provider_turn_complete_before_final_transcript_still_waits_for_text() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    assert gate.mark_provider_turn_complete() is True
    assert gate.take_resolution() is None
    assert gate.receive_final_transcript("do location onboarding") is None
    assert gate.take_resolution() == ("turn_123", "do location onboarding")


def test_post_endpoint_pcm_is_ignored_without_opening_another_turn() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    assert gate.mark_provider_turn_complete() is True
    # A frame already queued on the client side after the fixed endpoint is
    # neither a sequence failure nor accepted command PCM. The relay drops it
    # before it can reach Gemini and create a stray untagged activity turn.
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 2}) == "post_endpoint_ignored"
    assert turn.last_sequence == 1


def test_normal_client_end_is_rejected_and_never_routes_a_partial_command() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    ended, end_error = gate.end(_end())
    assert ended is None
    assert end_error == "client_end_not_supported"
    # The relay fails and reconnects after an obsolete successful-release
    # frame; no later untagged provider fragment can route this command.
    assert gate.fail() == "turn_123"
    assert gate.receive_final_transcript("do location onboarding") is None
    assert gate.mark_provider_turn_complete() is False
    assert gate.take_resolution() is None


def test_claimed_durable_advance_cannot_be_retracted_by_a_late_transport_failure() -> None:
    """A post-claim fragment cannot hide a real durable settlement."""

    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)
    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    gate.receive_final_transcript("create a circle called Family")
    assert gate.mark_provider_turn_complete() is True
    assert gate.take_resolution() == ("turn_123", "create a circle called Family")

    assert gate.claim_durable_advance(turn_id="turn_123") is True
    # A delayed PCM/provider failure arrives after the command has crossed
    # into the server-owned durable adapter. It cannot replace its terminal
    # settlement with a false client-side failure.
    assert gate.fail() is None
    assert gate.may_emit_resolution_result(turn_id="turn_123") is True


def test_sequence_gap_fails_closed_instead_of_routing_a_partial_command() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None
    assert turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 2}) == "sequence_gap"
    assert gate.fail() == "turn_123"
    gate.receive_final_transcript("location onboarding")
    assert gate.mark_provider_turn_complete() is False
    assert gate.take_resolution() is None


def test_wrong_or_stale_turn_cannot_end_the_active_command() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "other_turn", "sequence": 1}) == "turn_mismatch"
    stale, end_error = gate.end(_end("other_turn", final_sequence=0))
    assert stale is None
    assert end_error == "turn_mismatch"
    # The relay fails the active turn on this error rather than letting a stale
    # end/control frame later route any audio it received.
    assert gate.fail() == "turn_123"
    gate.receive_final_transcript("do location onboarding")
    assert gate.mark_provider_turn_complete() is False
    assert gate.take_resolution() is None


def test_missing_provider_final_transcript_has_a_retryable_terminal_gate() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    assert gate.mark_provider_turn_complete() is True
    assert gate.take_resolution() is None
    assert gate.missing_final_transcript_after_completion(turn_id="turn_123") == "turn_123"
    assert gate.take_resolution() is None


def test_provider_boundary_without_final_text_is_retryable_and_never_resolves() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    assert gate.mark_provider_turn_complete() is True
    assert gate.missing_final_transcript_after_completion(turn_id="other_turn") is None
    assert gate.missing_final_transcript_after_completion(turn_id="turn_123") == "turn_123"
    assert gate.take_resolution() is None


def test_cancelled_command_never_routes_even_when_the_provider_finishes() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin(), provider_ready=True, context_ready=True)

    assert error is None
    assert turn is not None
    assert gate.accept_audio({"turnId": "turn_123", "sequence": 1}) is None
    ended, error = gate.end(_end(cancelled=True))

    assert error is None
    assert ended is not None and ended.cancelled is True
    gate.receive_final_transcript("do location onboarding")
    assert gate.mark_provider_turn_complete() is False
    assert gate.take_resolution() is None


def test_cancelled_turn_cannot_be_replaced_until_post_completion_boundary_drains() -> None:
    """Late untagged provider content from A must never route as command B."""

    gate = LocationCommandTurnGate()
    first, error = gate.begin(_begin("turn_a"), provider_ready=True, context_ready=True)
    assert error is None and first is not None
    assert gate.accept_audio({"turnId": "turn_a", "sequence": 1}) is None
    assert gate.end(_end("turn_a", cancelled=True))[1] is None
    # Cancellation forces a provider-session rollover. An old untagged
    # provider fragment can never be attached to B on this session.
    gate.fail()
    gate.mark_result_settled(turn_id="turn_a")

    second, error = gate.begin(_begin("turn_b"), provider_ready=True, context_ready=True)
    assert second is None
    assert error == "provider_turn_draining"

    # This old A fragment is ignored while A remains the gate owner.
    gate.receive_final_transcript("create a circle called old command")
    assert gate.take_resolution() is None


def test_cancelled_turn_cannot_be_replaced_until_untagged_provider_events_drain() -> None:
    gate = LocationCommandTurnGate()
    turn, error = gate.begin(_begin("turn_old"), provider_ready=True, context_ready=True)

    assert error is None and turn is not None
    assert gate.accept_audio({"turnId": "turn_old", "sequence": 1}) is None
    assert gate.end(_end("turn_old", cancelled=True))[1] is None
    # A final old-turn event may still arrive after cancel. It is discarded and
    # cannot become input for the next command because the relay reconnects.
    gate.receive_final_transcript("old command must never route")
    next_turn, next_error = gate.begin(_begin("turn_new"), provider_ready=True, context_ready=True)
    assert next_turn is None
    assert next_error == "provider_turn_draining"
    gate.mark_result_settled(turn_id="turn_old")
    next_turn, next_error = gate.begin(_begin("turn_new"), provider_ready=True, context_ready=True)
    assert next_turn is None
    assert next_error == "provider_turn_draining"
    assert gate.take_resolution() is None


class _BootstrapSocket:
    def __init__(self, frame: dict[str, object]) -> None:
        self.frame = frame

    async def receive_text(self) -> str:
        return json.dumps(self.frame)


@pytest.mark.asyncio
async def test_command_bootstrap_is_explicit_and_managed_only() -> None:
    """The standalone route accepts only the command protocol, not chat fallback."""

    command_relay = _location_command_relay_or_skip()
    frame = {
        "type": "runtime_bootstrap",
        "runtime_credential_mode": "hushh_managed_vertex",
        "location_command_protocol": LOCATION_COMMAND_PROTOCOL_VERSION,
    }
    await command_relay._module._receive_bootstrap(_BootstrapSocket(frame))  # type: ignore[arg-type]

    missing_protocol = dict(frame)
    missing_protocol.pop("location_command_protocol")
    with pytest.raises(ValueError, match="protocol_mismatch"):
        await command_relay._module._receive_bootstrap(  # type: ignore[arg-type]
            _BootstrapSocket(missing_protocol)
        )

    byok = dict(frame, runtime_credential_mode="byok", runtime_credential="client-secret")
    with pytest.raises(ValueError, match="managed_runtime_required"):
        await command_relay._module._receive_bootstrap(_BootstrapSocket(byok))  # type: ignore[arg-type]


@pytest.mark.asyncio
async def test_relay_accepts_pcm_sequence_metadata_nested_in_realtime_input(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Exercise the exact browser wire shape, not only the gate in isolation."""

    command_relay = _location_command_relay_or_skip()

    class _Socket:
        def __init__(self) -> None:
            pcm = b64encode(b"\x00\x01\x02\x03").decode("ascii")
            self._frames = [
                json.dumps({"type": "app_context", "contextId": "ctx", "appContext": {}}),
                json.dumps(
                    {
                        "type": "location_command_begin",
                        "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
                        "turnId": "turn_123",
                        "startSequence": 1,
                    }
                ),
                json.dumps(
                    {
                        "realtimeInput": {
                            "audio": {
                                "data": pcm,
                                "mimeType": "audio/pcm;rate=16000",
                            },
                            "locationCommand": {"turnId": "turn_123", "sequence": 1},
                        }
                    }
                ),
            ]
            self.sent: list[str] = []

        async def receive_text(self) -> str:
            if self._frames:
                return self._frames.pop(0)
            await asyncio.Event().wait()
            raise AssertionError("unreachable")

        async def send_text(self, value: str) -> None:
            self.sent.append(value)

    class _Session:
        setup_complete = object()

        def __init__(self) -> None:
            self.sent: list[dict[str, object]] = []
            self.audio_received = asyncio.Event()

        async def send_realtime_input(self, **kwargs: object) -> None:
            self.sent.append(kwargs)
            if "audio" in kwargs:
                self.audio_received.set()

        async def receive(self):
            await self.audio_received.wait()
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=SimpleNamespace(text="do location onboarding"),
                    interrupted=False,
                    turn_complete=False,
                )
            )
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=None,
                    interrupted=False,
                    turn_complete=True,
                )
            )

    class _Live:
        def __init__(self, session: _Session) -> None:
            self._session = session

        @asynccontextmanager
        async def connect(self, **_kwargs: object):
            yield self._session

    class _Runtime:
        async def plan(self, **kwargs: object) -> LocationCommandPlanV1:
            assert kwargs["transcript"] == "do location onboarding"
            return LocationCommandPlanV1(
                turn_id="turn_123",
                immediate_result=LocationCommandResultV1(
                    turn_id="turn_123",
                    outcome="ask",
                    reason_code="selection_required",
                ),
            )

        async def advance(
            self, plan: LocationCommandPlanV1, **_kwargs: object
        ) -> LocationCommandResultV1:
            assert plan.immediate_result is not None
            return plan.immediate_result

    socket = _Socket()
    session = _Session()
    client = SimpleNamespace(aio=SimpleNamespace(live=_Live(session)))

    monkeypatch.setattr(command_relay, "get_location_command_runtime", lambda: _Runtime())

    await command_relay._run_location_command_relay(
        socket,  # type: ignore[arg-type]
        uid="owner",
        client=client,
        model=DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL,
    )

    assert any("audio" in frame for frame in session.sent)
    assert not any("activity_start" in frame for frame in session.sent)
    assert not any("activity_end" in frame for frame in session.sent)
    wire = "\n".join(socket.sent)
    payloads = [json.loads(frame) for frame in socket.sent]
    assert {"serverContent": {"turnComplete": True}} in payloads
    assert any(
        payload.get("locationCommandResult", {}).get("outcome") == "ask" for payload in payloads
    )
    # A provider turn is untagged. After a terminal command result and the
    # post-completion drain, the relay must rotate instead of accepting a
    # second physical hold on this Live session.
    assert any(
        payload.get("sessionEnded", {}).get("reason") == "location_command_boundary_rollover"
        for payload in payloads
    )
    assert "turn_mismatch" not in wire
    assert "do location onboarding" not in wire


@pytest.mark.asyncio
async def test_relay_returns_retry_when_provider_completes_without_a_final_transcript(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A provider endpoint without text cannot select or route a command."""

    command_relay = _location_command_relay_or_skip()

    class _Socket:
        def __init__(self) -> None:
            pcm = b64encode(b"\x00\x01\x02\x03").decode("ascii")
            self._frames = [
                json.dumps({"type": "app_context", "contextId": "ctx", "appContext": {}}),
                json.dumps(
                    {
                        "type": "location_command_begin",
                        "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
                        "turnId": "turn_early_provider",
                        "startSequence": 1,
                    }
                ),
                json.dumps(
                    {
                        "realtimeInput": {
                            "audio": {
                                "data": pcm,
                                "mimeType": "audio/pcm;rate=16000",
                            },
                            "locationCommand": {
                                "turnId": "turn_early_provider",
                                "sequence": 1,
                            },
                        }
                    }
                ),
            ]
            self.sent: list[str] = []

        async def receive_text(self) -> str:
            if self._frames:
                return self._frames.pop(0)
            await asyncio.Event().wait()
            raise AssertionError("unreachable")

        async def send_text(self, value: str) -> None:
            self.sent.append(value)

    class _Session:
        setup_complete = object()

        def __init__(self) -> None:
            self.audio_received = asyncio.Event()
            self.sent: list[dict[str, object]] = []

        async def send_realtime_input(self, **kwargs: object) -> None:
            self.sent.append(kwargs)
            if "audio" in kwargs:
                self.audio_received.set()

        async def receive(self):
            await self.audio_received.wait()
            # Automatic activity detection is allowed to close speech after
            # contiguous PCM, but it must never route without final text.
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=None,
                    interrupted=False,
                    turn_complete=True,
                )
            )
            # Keep the provider side alive through the final-transcript grace
            # period. A normal provider socket remains open at this point;
            # ending this fake generator would instead assert a provider
            # outage before the relay can issue its retry card.
            await asyncio.Event().wait()

    class _Live:
        def __init__(self, session: _Session) -> None:
            self._session = session

        @asynccontextmanager
        async def connect(self, **_kwargs: object):
            yield self._session

    class _Runtime:
        calls = 0

        async def plan(self, **_kwargs: object) -> LocationCommandPlanV1:
            self.calls += 1
            raise AssertionError("early provider completion must not route")

    socket = _Socket()
    session = _Session()
    runtime = _Runtime()
    client = SimpleNamespace(aio=SimpleNamespace(live=_Live(session)))

    monkeypatch.setattr(command_relay, "get_location_command_runtime", lambda: runtime)

    await command_relay._run_location_command_relay(
        socket,  # type: ignore[arg-type]
        uid="owner",
        client=client,
        model=DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL,
    )

    assert runtime.calls == 0
    assert any("audio" in frame for frame in session.sent)
    assert not any("activity_start" in frame for frame in session.sent)
    assert not any("activity_end" in frame for frame in session.sent)
    wire = "\n".join(socket.sent)
    payloads = [json.loads(frame) for frame in socket.sent]
    assert "final_transcript_missing" in wire
    assert any(
        payload.get("locationCommandResult", {}).get("outcome") == "failed" for payload in payloads
    )
    assert {"serverContent": {"turnComplete": True}} in payloads


@pytest.mark.asyncio
async def test_resolution_timeout_rolls_the_provider_and_discards_late_result(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A stalled selector cannot strand the next hold or publish late UI."""

    command_relay = _location_command_relay_or_skip()
    # This is deliberately shorter than the fixed 250ms provider grace so the
    # test proves the grace runs while the cancelled resolver is still alive.
    monkeypatch.setattr(command_relay, "_LOCATION_COMMAND_RESOLUTION_TIMEOUT_SECONDS", 0.01)

    class _Socket:
        _DISCONNECT = object()

        def __init__(self) -> None:
            self.frames: asyncio.Queue[object] = asyncio.Queue()
            self.sent: list[str] = []
            self.timeout_sent = asyncio.Event()
            self.second_result_sent = asyncio.Event()

        async def receive_text(self) -> str:
            frame = await self.frames.get()
            if frame is self._DISCONNECT:
                raise command_relay.WebSocketDisconnect()
            return str(frame)

        async def send_text(self, value: str) -> None:
            self.sent.append(value)
            payload = json.loads(value)
            result = payload.get("locationCommandResult")
            if not isinstance(result, dict):
                return
            if result.get("reasonCode") == "resolution_timeout":
                self.timeout_sent.set()
            if result.get("reasonCode") == "second_turn_ready":
                self.second_result_sent.set()

        async def feed(self, frame: dict[str, object] | object) -> None:
            await self.frames.put(frame if frame is self._DISCONNECT else json.dumps(frame))

    class _Session:
        setup_complete = object()

        def __init__(self) -> None:
            self.audio_packets: asyncio.Queue[None] = asyncio.Queue()
            self.audio_packet_count = 0

        async def send_realtime_input(self, **kwargs: object) -> None:
            if "audio" in kwargs:
                self.audio_packet_count += 1
                await self.audio_packets.put(None)

        async def receive(self):
            await self.audio_packets.get()
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=SimpleNamespace(text="first location command"),
                    interrupted=False,
                    turn_complete=False,
                )
            )
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=None,
                    interrupted=False,
                    turn_complete=True,
                )
            )
            while True:
                await asyncio.Event().wait()

    class _Live:
        def __init__(self, session: _Session) -> None:
            self._session = session

        @asynccontextmanager
        async def connect(self, **_kwargs: object):
            yield self._session

    class _Runtime:
        def __init__(self) -> None:
            self.calls = 0
            self.first_cancelled = asyncio.Event()
            self.allow_late_return = asyncio.Event()
            self.late_returned = asyncio.Event()

        async def plan(self, **kwargs: object) -> LocationCommandPlanV1:
            self.calls += 1
            if self.calls == 1:
                try:
                    await asyncio.Event().wait()
                except asyncio.CancelledError:
                    self.first_cancelled.set()
                    # Deliberately ignore cancellation long enough to prove a
                    # stale action result cannot re-enter the websocket lane.
                    await self.allow_late_return.wait()
                    self.late_returned.set()
                    return LocationCommandPlanV1(
                        turn_id=str(kwargs["turn_id"]),
                        immediate_result=LocationCommandResultV1(
                            turn_id=str(kwargs["turn_id"]),
                            outcome="interaction_required",
                            action_id="workflow.setup.location",
                            reason_code="late_result_must_not_render",
                        ),
                    )
            return LocationCommandPlanV1(
                turn_id=str(kwargs["turn_id"]),
                immediate_result=LocationCommandResultV1(
                    turn_id=str(kwargs["turn_id"]),
                    outcome="ask",
                    reason_code="second_turn_ready",
                ),
            )

        async def advance(
            self, plan: LocationCommandPlanV1, **_kwargs: object
        ) -> LocationCommandResultV1:
            assert plan.immediate_result is not None
            return plan.immediate_result

    socket = _Socket()
    session = _Session()
    runtime = _Runtime()
    client = SimpleNamespace(aio=SimpleNamespace(live=_Live(session)))
    pcm = b64encode(b"\x00\x01\x02\x03").decode("ascii")

    monkeypatch.setattr(command_relay, "get_location_command_runtime", lambda: runtime)

    async def _send_turn(turn_id: str) -> None:
        await socket.feed(
            {
                "type": "location_command_begin",
                "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
                "turnId": turn_id,
                "startSequence": 1,
            }
        )
        await socket.feed(
            {
                "realtimeInput": {
                    "audio": {"data": pcm, "mimeType": "audio/pcm;rate=16000"},
                    "locationCommand": {"turnId": turn_id, "sequence": 1},
                }
            }
        )

    await socket.feed({"type": "app_context", "contextId": "ctx", "appContext": {}})
    await _send_turn("turn_first")
    relay = asyncio.create_task(
        command_relay._run_location_command_relay(
            socket,  # type: ignore[arg-type]
            uid="owner",
            client=client,
            model=DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL,
        )
    )
    try:
        await asyncio.wait_for(socket.timeout_sent.wait(), timeout=1)
        await asyncio.wait_for(runtime.first_cancelled.wait(), timeout=1)

        # A cancellation-ignoring semantic task may eventually return, but it
        # owns no output after its deadline. The standalone relay terminates
        # this command boundary immediately instead of accepting another
        # untagged provider turn on the same socket.
        runtime.allow_late_return.set()
        await asyncio.wait_for(runtime.late_returned.wait(), timeout=1)
        await asyncio.wait_for(relay, timeout=1)

        results = [
            json.loads(frame).get("locationCommandResult")
            for frame in socket.sent
            if isinstance(json.loads(frame).get("locationCommandResult"), dict)
        ]
        assert [item.get("reasonCode") for item in results].count("resolution_timeout") == 1
        assert "late_result_must_not_render" not in {item.get("reasonCode") for item in results}
        assert session.audio_packet_count == 1
        assert any(
            json.loads(frame).get("sessionEnded", {}).get("reason") == "resolution_failed"
            for frame in socket.sent
        )
    finally:
        if not relay.done():
            await socket.feed(_Socket._DISCONNECT)
            await asyncio.wait_for(relay, timeout=1)


@pytest.mark.asyncio
async def test_durable_advance_is_not_reported_as_a_semantic_routing_timeout(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Once a selected plan enters a durable adapter, it owns settlement."""

    command_relay = _location_command_relay_or_skip()
    monkeypatch.setattr(command_relay, "_LOCATION_COMMAND_RESOLUTION_TIMEOUT_SECONDS", 0.01)

    class _Socket:
        _DISCONNECT = object()

        def __init__(self) -> None:
            self.frames: asyncio.Queue[object] = asyncio.Queue()
            self.sent: list[str] = []
            self.working_sent = asyncio.Event()
            self.result_sent = asyncio.Event()

        async def receive_text(self) -> str:
            frame = await self.frames.get()
            if frame is self._DISCONNECT:
                raise command_relay.WebSocketDisconnect()
            return str(frame)

        async def send_text(self, value: str) -> None:
            self.sent.append(value)
            payload = json.loads(value)
            state = payload.get("locationCommandState")
            if isinstance(state, dict) and state.get("state") == "working":
                self.working_sent.set()
            result = payload.get("locationCommandResult")
            if isinstance(result, dict) and result.get("settlement") == "verified":
                self.result_sent.set()

        async def feed(self, frame: dict[str, object] | object) -> None:
            await self.frames.put(frame if frame is self._DISCONNECT else json.dumps(frame))

    class _Session:
        setup_complete = object()

        def __init__(self) -> None:
            self.audio_received = asyncio.Event()

        async def send_realtime_input(self, **kwargs: object) -> None:
            if "audio" in kwargs:
                self.audio_received.set()

        async def receive(self):
            await self.audio_received.wait()
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=SimpleNamespace(text="create my location circle"),
                    interrupted=False,
                    turn_complete=False,
                )
            )
            yield SimpleNamespace(
                server_content=SimpleNamespace(
                    input_transcription=None,
                    interrupted=False,
                    turn_complete=True,
                )
            )
            while True:
                await asyncio.Event().wait()

    class _Live:
        def __init__(self, session: _Session) -> None:
            self._session = session

        @asynccontextmanager
        async def connect(self, **_kwargs: object):
            yield self._session

    class _Runtime:
        def __init__(self) -> None:
            self.advance_started = asyncio.Event()
            self.allow_settlement = asyncio.Event()

        async def plan(self, **kwargs: object) -> LocationCommandPlanV1:
            return LocationCommandPlanV1(
                turn_id=str(kwargs["turn_id"]),
                selected_capability_id="location.create_circle",
                disposition="EXECUTE_SERVER_VERIFIED",
                slots={"name": "My Circle"},
            )

        async def advance(
            self, plan: LocationCommandPlanV1, **_kwargs: object
        ) -> LocationCommandResultV1:
            assert plan.requires_durable_advance is True
            self.advance_started.set()
            await self.allow_settlement.wait()
            return LocationCommandResultV1(
                turn_id=plan.turn_id,
                outcome="execute_started",
                action_id="location.create_circle",
                settlement="verified",
            )

    socket = _Socket()
    session = _Session()
    runtime = _Runtime()
    client = SimpleNamespace(aio=SimpleNamespace(live=_Live(session)))
    pcm = b64encode(b"\x00\x01\x02\x03").decode("ascii")

    monkeypatch.setattr(command_relay, "get_location_command_runtime", lambda: runtime)

    await socket.feed({"type": "app_context", "contextId": "ctx", "appContext": {}})
    await socket.feed(
        {
            "type": "location_command_begin",
            "protocolVersion": LOCATION_COMMAND_PROTOCOL_VERSION,
            "turnId": "turn_durable",
            "startSequence": 1,
        }
    )
    await socket.feed(
        {
            "realtimeInput": {
                "audio": {"data": pcm, "mimeType": "audio/pcm;rate=16000"},
                "locationCommand": {"turnId": "turn_durable", "sequence": 1},
            }
        }
    )
    relay = asyncio.create_task(
        command_relay._run_location_command_relay(
            socket,  # type: ignore[arg-type]
            uid="owner",
            client=client,
            model=DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL,
        )
    )
    try:
        await asyncio.wait_for(runtime.advance_started.wait(), timeout=1)
        await asyncio.wait_for(socket.working_sent.wait(), timeout=1)
        # Deliberately exceed the semantic selection deadline: the durable
        # adapter is allowed to settle through its own idempotent lifecycle.
        await asyncio.sleep(0.03)
        assert not any(
            json.loads(frame).get("locationCommandResult", {}).get("reasonCode")
            == "resolution_timeout"
            for frame in socket.sent
        )
        runtime.allow_settlement.set()
        await asyncio.wait_for(socket.result_sent.wait(), timeout=1)
        results = [
            json.loads(frame).get("locationCommandResult")
            for frame in socket.sent
            if isinstance(json.loads(frame).get("locationCommandResult"), dict)
        ]
        assert any(
            item.get("actionId") == "location.create_circle"
            and item.get("settlement") == "verified"
            for item in results
        )
    finally:
        await socket.feed(_Socket._DISCONNECT)
        await asyncio.wait_for(relay, timeout=1)


@pytest.mark.asyncio
async def test_workflow_result_is_a_typed_card_without_transcript_or_slots(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    projection = {
        "schema_version": "one.location_turn_projection.v1",
        "graph_revision": "graph_revision",
        "brain_revision": "brain_revision",
        "context_revision": "ctx_" + "a" * 24,
        "candidates": [
            {
                "candidate_id": "workflow.setup.location",
                "disposition": "EXECUTE_SERVER_VERIFIED",
                "public_slot_types": [],
            }
        ],
        "selection_contract": {
            "field": "candidate_id_or_ASK",
            "allowed_values": ["workflow.setup.location", "ASK"],
        },
        "retrieval_status": "READY",
        "reason_code": "semantic",
    }

    async def selector(_routing_text: str, _turn: object) -> dict[str, object]:
        return {"candidate_id_or_ASK": "workflow.setup.location", "slots": {}}

    runtime = LocationCommandRuntime(
        selector=selector, semantic_retriever=lambda **_kwargs: projection
    )

    async def active_run(*, user_id: str):
        assert user_id == "owner"
        return None, None

    start_calls: list[tuple[str, str]] = []

    async def start_run(*, user_id: str, context_revision: str):
        assert user_id == "owner"
        assert context_revision == "ctx-current"
        start_calls.append((user_id, context_revision))
        return (
            {
                "workflow_id": "workflow.setup.location",
                "workflow_version": 2,
                "graph_revision": "graph_revision",
                "run_id": "run_opaque",
                "revision": 3,
                "status": "interaction_required",
                "step": "location.onboarding.permission",
                "completion_claim_allowed": False,
                "interaction": {
                    "directive_id": "locdirective_opaque",
                    "surface_id": "render.one_location_workflow_card",
                    "kind": "technical_interaction",
                    "title_key": "location.permission.title",
                    "body_key": "location.permission.body",
                    "allowed_actions": ["request_permission", "pause"],
                    "expires_at": "2030-01-01T00:00:00Z",
                    "lease_id": "loclease_opaque",
                    "run_revision": 3,
                },
            },
            None,
        )

    monkeypatch.setattr(runtime, "_active_run", active_run)
    monkeypatch.setattr(runtime, "_start_or_resume_workflow", start_run)
    monkeypatch.setattr(
        location_command_module, "build_location_brain_snapshot", lambda **_kwargs: {}
    )

    plan = await runtime.plan(
        turn_id="turn_123",
        transcript="Do the Location onboarding from 40.7128, -74.0060",
        user_id="owner",
    )
    assert plan.requires_durable_advance is True
    # Semantic selection is the only deadline-bound phase. It may read state,
    # but it cannot create/resume a workflow before the relay claims a durable
    # advance for the provider-owned final-transcript/turnComplete boundary.
    assert start_calls == []

    test_consent_token = "test-" + "consent"
    result = await runtime.advance(
        plan,
        user_id="owner",
        consent_token=test_consent_token,
        context_revision="ctx-current",
    )
    assert start_calls == [("owner", "ctx-current")]
    payload = result.wire_payload()

    assert payload["outcome"] == "interaction_required"
    assert payload["directive"]["surfaceId"] == "render.one_location_workflow_card"
    encoded = json.dumps(payload)
    assert "40.7128" not in encoded
    assert test_consent_token not in encoded
    assert "onboarding from" not in encoded


@pytest.mark.asyncio
async def test_selector_ask_does_not_start_a_workflow(monkeypatch: pytest.MonkeyPatch) -> None:
    projection = {
        "schema_version": "one.location_turn_projection.v1",
        "graph_revision": "graph_revision",
        "brain_revision": "brain_revision",
        "context_revision": "ctx_" + "a" * 24,
        "candidates": [
            {
                "candidate_id": "workflow.setup.location",
                "disposition": "EXECUTE_SERVER_VERIFIED",
                "public_slot_types": [],
            }
        ],
        "selection_contract": {
            "field": "candidate_id_or_ASK",
            "allowed_values": ["workflow.setup.location", "ASK"],
        },
        "retrieval_status": "READY",
        "reason_code": "semantic",
    }

    async def selector(_routing_text: str, _turn: object) -> dict[str, object]:
        return {"candidate_id_or_ASK": "ASK"}

    runtime = LocationCommandRuntime(
        selector=selector, semantic_retriever=lambda **_kwargs: projection
    )

    async def active_run(*, user_id: str):
        return None, None

    async def must_not_start(**_kwargs: object):
        raise AssertionError("ASK must not start Location onboarding")

    monkeypatch.setattr(runtime, "_active_run", active_run)
    monkeypatch.setattr(runtime, "_start_or_resume_workflow", must_not_start)
    monkeypatch.setattr(
        location_command_module, "build_location_brain_snapshot", lambda **_kwargs: {}
    )

    result = await runtime.resolve(
        turn_id="turn_123",
        transcript="something unrelated",
        user_id="owner",
        consent_token=None,
        context_revision="",
    )

    assert result.outcome == "ask"
    assert result.reason_code == "selection_required"


def test_transcribe_model_is_hard_pinned_even_when_deployment_env_is_altered(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("HUSHH_LOCATION_COMMAND_TRANSCRIBE_MODEL", raising=False)
    assert location_command_transcribe_model_id() == DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL
    monkeypatch.setenv("HUSHH_LOCATION_COMMAND_TRANSCRIBE_MODEL", "gemini-unreviewed")
    assert location_command_transcribe_model_id() == DEFAULT_LOCATION_COMMAND_TRANSCRIBE_MODEL


def test_command_runtime_flag_defaults_off_and_is_server_owned(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("ENVIRONMENT", "uat")
    monkeypatch.delenv("HUSHH_LOCATION_COMMAND_RUNTIME_ENABLED", raising=False)
    assert location_command_runtime_enabled() is False
    monkeypatch.setenv("HUSHH_LOCATION_COMMAND_RUNTIME_ENABLED", "true")
    assert location_command_runtime_enabled() is True

    monkeypatch.setenv("ENVIRONMENT", "development")
    assert location_command_runtime_enabled() is False
    monkeypatch.setenv("ENVIRONMENT", "production")
    assert location_command_runtime_enabled() is False


def test_live_transcribe_config_uses_text_only_automatic_vad_and_observed_setup() -> None:
    from google.genai import types as genai_types

    command_relay = _location_command_relay_or_skip()
    config = command_relay._build_location_command_live_config(genai_types)
    assert config.response_modalities == [genai_types.Modality.TEXT]
    assert config.input_audio_transcription is not None
    assert config.realtime_input_config is not None
    assert config.realtime_input_config.automatic_activity_detection is not None
    assert config.realtime_input_config.automatic_activity_detection.disabled is False

    class _Session:
        setup_complete = object()

    class _NoSetupSession:
        setup_complete = None

    assert command_relay._location_command_provider_setup_observed(_Session()) is True
    assert command_relay._location_command_provider_setup_observed(_NoSetupSession()) is False


def test_navigation_result_is_bounded_to_a_compiled_query_free_route(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        location_command_module,
        "get_capability",
        lambda _capability_id: {
            "execution": {"target": {"target": "/one/location"}},
            "navigation": {"fallback": "/one/location", "routes": ["/one/location"]},
        },
    )
    directive = _safe_navigation_directive("route.one_location")
    assert directive == {
        "schemaVersion": "one.location_navigation_directive.v1",
        "capabilityId": "route.one_location",
        "route": "/one/location",
        "settlement": "route_settlement_required",
    }

    result = LocationCommandResultV1(
        turn_id="turn_123",
        outcome="navigate",
        action_id="route.one_location",
        navigation=directive,
    ).wire_payload()
    encoded = json.dumps(result)
    assert "transcript" not in encoded
    assert "?" not in encoded


def test_verified_circle_result_has_an_approved_identifier_only_status_card() -> None:
    card = location_command_module._verified_status_card("location.create_circle")
    payload = LocationCommandResultV1(
        turn_id="turn_123",
        outcome="execute_started",
        action_id="location.create_circle",
        status_card=card,
        settlement="verified",
    ).wire_payload()

    assert payload["statusCard"] == {
        "schemaVersion": "one.location_command_status_card.v1",
        "surfaceId": "render.data_card",
        "cardId": "one.location.command.circle_verified.v1",
        "actionId": "location.create_circle",
        "settlement": "verified",
    }
    assert "name" not in json.dumps(payload)


@pytest.mark.asyncio
async def test_missing_circle_name_returns_only_the_server_leased_typed_form(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    observed: dict[str, object] = {}
    directive = {
        "schemaVersion": "one.location_circle_name_interaction.v1",
        "actionId": "location.create_circle",
        "surfaceId": "render.form",
        "formId": "one.location.create_circle_name.v1",
        "directiveId": f"loccirclecmd_{'a' * 32}",
        "run": {
            "runId": "run_abcdefghijklmnop",
            "revision": 2,
            "graphRevision": "a" * 64,
            "contextRevision": "ctx-1",
            "status": "needs_input",
        },
        "lease": {"leaseId": f"loccirclelease_2000000000_{'b' * 64}", "runRevision": 2},
        "expiresAt": "2099-09-10T00:00:00.000Z",
        "titleKey": "one.location.circle_name.title",
        "bodyKey": "one.location.circle_name.body",
        "fields": [{"fieldId": "name", "type": "string", "required": True, "maxLength": 80}],
        "submitKey": "one.location.circle_name.submit",
    }

    class _FormService:
        async def issue(self, **kwargs: object):
            observed.update(kwargs)
            return SimpleNamespace(wire_projection=lambda: directive)

    async def unexpected_dispatch(**_kwargs: object):
        raise AssertionError("a missing name must not dispatch Circle creation")

    monkeypatch.setattr(
        location_command_module,
        "get_location_circle_name_interaction_service",
        lambda: _FormService(),
    )
    monkeypatch.setattr(
        location_command_module, "_dispatch_circle_server_direct", unexpected_dispatch
    )

    result = await LocationCommandRuntime()._execute_circle(
        user_id="owner-1",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="turn_123",
        slots={},
        context_revision="ctx-1",
    )

    assert observed == {"user_id": "owner-1", "context_revision": "ctx-1"}
    assert result.outcome == "interaction_required"
    assert result.action_id == "location.create_circle"
    payload = result.wire_payload()
    assert payload["circleNameDirective"] == directive
    assert "ask" not in payload
    assert "Family" not in json.dumps(payload)


@pytest.mark.asyncio
async def test_unquoted_circle_name_is_local_only_and_never_reaches_routing_providers(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A free-form Circle label is product input, not model routing context."""

    projection = {
        "schema_version": "one.location_turn_projection.v1",
        "graph_revision": "graph_revision",
        "brain_revision": "brain_revision",
        "context_revision": "ctx_" + "a" * 24,
        "candidates": [
            {
                "candidate_id": "location.create_circle",
                "disposition": "EXECUTE_SERVER_VERIFIED",
                "public_slot_types": [{"name": "name", "type": "string"}],
            }
        ],
        "selection_contract": {
            "field": "candidate_id_or_ASK",
            "allowed_values": ["location.create_circle", "ASK"],
        },
        "retrieval_status": "READY",
        "reason_code": "semantic",
    }
    observed: dict[str, object] = {}
    secret_name = "Zircon Willow Tundra"

    def retriever(**kwargs: object) -> dict[str, object]:
        observed["embedding_query"] = kwargs["query"]
        return projection

    async def selector(routing_text: str, _projection: object) -> dict[str, object]:
        observed["selector_query"] = routing_text
        return {"candidate_id_or_ASK": "location.create_circle"}

    runtime = LocationCommandRuntime(selector=selector, semantic_retriever=retriever)

    async def active_run(*, user_id: str):
        assert user_id == "owner"
        return None, None

    async def execute_circle(**kwargs: object) -> LocationCommandResultV1:
        observed["slots"] = kwargs["slots"]
        return LocationCommandResultV1(
            turn_id="turn_123",
            outcome="ask",
            action_id="location.create_circle",
            reason_code="test_only",
        )

    monkeypatch.setattr(runtime, "_active_run", active_run)
    monkeypatch.setattr(runtime, "_execute_circle", execute_circle)
    monkeypatch.setattr(
        location_command_module, "build_location_brain_snapshot", lambda **_kwargs: {}
    )

    result = await runtime.resolve(
        turn_id="turn_123",
        transcript=f"Please create a circle called {secret_name}",
        user_id="owner",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        context_revision="ctx-current",
    )

    assert result.outcome == "ask"
    assert observed["slots"] == {"name": secret_name}
    for provider_input in (observed["embedding_query"], observed["selector_query"]):
        assert secret_name.lower() not in str(provider_input).lower()
        assert "create" in str(provider_input).lower()
        assert "circle" in str(provider_input).lower()


@pytest.mark.asyncio
async def test_unquoted_address_never_reaches_location_embedding_or_selector(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    projection = {
        "schema_version": "one.location_turn_projection.v1",
        "graph_revision": "graph_revision",
        "brain_revision": "brain_revision",
        "context_revision": "ctx_" + "a" * 24,
        "candidates": [
            {
                "candidate_id": "workflow.setup.location",
                "disposition": "EXECUTE_SERVER_VERIFIED",
                "public_slot_types": [],
            }
        ],
        "selection_contract": {
            "field": "candidate_id_or_ASK",
            "allowed_values": ["workflow.setup.location", "ASK"],
        },
        "retrieval_status": "READY",
        "reason_code": "semantic",
    }
    observed: list[str] = []
    address = "742 Evergreen Terrace"

    def retriever(**kwargs: object) -> dict[str, object]:
        observed.append(str(kwargs["query"]))
        return projection

    async def selector(routing_text: str, _projection: object) -> dict[str, object]:
        observed.append(routing_text)
        return {"candidate_id_or_ASK": "ASK"}

    runtime = LocationCommandRuntime(selector=selector, semantic_retriever=retriever)

    async def active_run(*, user_id: str):
        return None, None

    monkeypatch.setattr(runtime, "_active_run", active_run)
    monkeypatch.setattr(
        location_command_module, "build_location_brain_snapshot", lambda **_kwargs: {}
    )

    result = await runtime.resolve(
        turn_id="turn_123",
        transcript=f"Please do location onboarding at {address}",
        user_id="owner",
        consent_token=None,
        context_revision="ctx-current",
    )

    assert result.outcome == "ask"
    assert len(observed) == 2
    assert all(address.lower() not in value.lower() for value in observed)


def test_location_command_selector_rejects_developer_api_key_binding(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    class _DeveloperBinding:
        auth_mode = "developer_api_key"

        @classmethod
        def from_environment(cls):
            return cls()

        def build_direct_client(self, **_kwargs: object) -> object:
            raise AssertionError("Developer API key must not build a Location selector client")

    monkeypatch.setattr(location_command_module, "ManagedGeminiRuntimeBinding", _DeveloperBinding)

    assert (
        location_command_module._build_managed_location_command_text_client(model="gemini-default")
        is None
    )


def test_circle_execution_scope_is_server_derived_opaque_and_slot_normalized() -> None:
    first = location_command_module._derive_circle_execution_scope(
        user_id="owner_123",
        name="  Family   Circle ",
        replay_generation=100,
    )
    same_normalized_slots = location_command_module._derive_circle_execution_scope(
        user_id="owner_123",
        name="Family Circle",
        replay_generation=100,
    )
    another_owner = location_command_module._derive_circle_execution_scope(
        user_id="owner_456",
        name="Family Circle",
        replay_generation=100,
    )
    another_name = location_command_module._derive_circle_execution_scope(
        user_id="owner_123",
        name="Friends Circle",
        replay_generation=100,
    )
    later_generation = location_command_module._derive_circle_execution_scope(
        user_id="owner_123",
        name="Family Circle",
        replay_generation=101,
    )

    assert first is not None
    assert first == same_normalized_slots
    assert first != another_owner
    assert first != another_name
    assert first != later_generation
    assert first.startswith("lcc1_")
    # The scope is a server-secret HMAC, never a client turn, owner, or name.
    assert "owner_123" not in first
    assert "Family" not in first


@pytest.mark.asyncio
async def test_circle_replay_with_new_transport_turn_resumes_the_durable_run(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A lost response must not turn a retry into a second Circle mutation."""

    dispatches: list[dict[str, str | None]] = []

    async def dispatch(
        *,
        user_id: str,
        consent_token: str,
        name: str,
        execution_scope: str,
        resume_run_id: str | None,
    ) -> dict[str, str]:
        assert user_id == "owner_123"
        assert consent_token == "test-consent"
        assert name == "Family Circle"
        dispatches.append({"execution_scope": execution_scope, "resume_run_id": resume_run_id})
        return {"status": "completed"}

    monkeypatch.setattr(location_command_module, "_dispatch_circle_server_direct", dispatch)
    replay_results = iter([(None, None), ("run_replay_123", None)])

    async def find_replay(**_kwargs: object) -> tuple[str | None, str | None]:
        return next(replay_results)

    monkeypatch.setattr(location_command_module, "_find_recent_circle_replay_run_id", find_replay)
    runtime = LocationCommandRuntime()

    first = await runtime._execute_circle(
        user_id="owner_123",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="client_turn_lost_response",
        slots={"name": " Family   Circle "},
    )
    replay = await runtime._execute_circle(
        user_id="owner_123",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="client_turn_after_reconnect",
        slots={"name": "Family Circle"},
    )

    assert first.outcome == replay.outcome == "execute_started"
    assert [item["resume_run_id"] for item in dispatches] == [None, "run_replay_123"]
    assert dispatches[0]["execution_scope"] not in {
        "client_turn_lost_response",
        "client_turn_after_reconnect",
    }
    assert str(dispatches[0]["execution_scope"]).startswith("lcc1_")


@pytest.mark.asyncio
async def test_later_intentional_same_name_circle_uses_a_fresh_server_scope(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Same display names remain legal after the bounded replay interval."""

    scopes: list[str] = []

    async def no_replay(**_kwargs: object) -> tuple[str | None, str | None]:
        return None, None

    async def dispatch(
        *,
        execution_scope: str,
        resume_run_id: str | None,
        **_kwargs: object,
    ) -> dict[str, str]:
        assert resume_run_id is None
        scopes.append(execution_scope)
        return {"status": "completed"}

    generations = iter([100, 101])
    monkeypatch.setattr(location_command_module, "_find_recent_circle_replay_run_id", no_replay)
    monkeypatch.setattr(location_command_module, "_dispatch_circle_server_direct", dispatch)
    monkeypatch.setattr(
        location_command_module,
        "_circle_replay_generation",
        lambda **_kwargs: next(generations),
    )
    runtime = LocationCommandRuntime()

    first = await runtime._execute_circle(
        user_id="owner_123",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="client_turn_initial",
        slots={"name": "Family Circle"},
    )
    later = await runtime._execute_circle(
        user_id="owner_123",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="client_turn_later",
        slots={"name": "Family Circle"},
    )

    assert first.outcome == later.outcome == "execute_started"
    assert len(scopes) == 2
    assert scopes[0] != scopes[1]


@pytest.mark.asyncio
async def test_circle_replay_lookup_is_owner_graph_slot_bound_and_private(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    observed: dict[str, object] = {}

    class _Store:
        async def find_recent_verified_matching_slots(self, **kwargs: object):
            observed.update(kwargs)
            return SimpleNamespace(run_id="run_recent_verified")

    monkeypatch.setattr(
        location_command_module,
        "load_capability_graph",
        lambda: {"revision": "graph_current"},
    )
    monkeypatch.setattr(location_command_module, "get_capability_run_store", lambda: _Store())

    run_id, error = await location_command_module._find_recent_circle_replay_run_id(
        user_id="owner_123",
        name="Family Circle",
    )

    assert (run_id, error) == ("run_recent_verified", None)
    assert observed == {
        "user_id": "owner_123",
        "capability_id": "location.create_circle",
        "graph_revision": "graph_current",
        "slots": {"name": "Family Circle"},
        "replay_window_seconds": 120,
    }


@pytest.mark.asyncio
async def test_circle_execution_fails_closed_without_server_signing_scope(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    class _MissingSettings:
        @property
        def app_signing_key(self) -> str:
            raise ValueError("missing")

    monkeypatch.setattr(
        location_command_module,
        "get_core_security_settings",
        lambda: _MissingSettings(),
    )

    async def no_replay(**_kwargs: object) -> tuple[str | None, str | None]:
        return None, None

    monkeypatch.setattr(location_command_module, "_find_recent_circle_replay_run_id", no_replay)
    runtime = LocationCommandRuntime()
    result = await runtime._execute_circle(
        user_id="owner_123",
        consent_token="test-consent",  # noqa: S106 - synthetic test token
        turn_id="client_turn_123",
        slots={"name": "Family Circle"},
    )

    assert result.outcome == "failed"
    assert result.reason_code == "idempotency_unavailable"
