using System.Security.Cryptography;
using System.Text;

namespace OneWindows.Consent;

/// <summary>
/// C# port of hushh_mcp/consent/token.py's issue_token/validate_token/_sign.
/// Field order, delimiter choice, and validation-error ordering (signature
/// before expiry, expiry before scope) are kept byte-for-byte identical to
/// the Python source so tokens are interchangeable between the desktop
/// backend and this daemon. Verified against golden vectors generated by
/// the real Python codec -- see OneWindows.Consent.Tests and
/// scripts/generate_golden_vectors.py.
///
/// Scope enforcement (expectedScope) delegates to ScopeMatcher, itself a
/// verified port of scope_matches()/DynamicScopeGenerator's pure parsing
/// logic. Not ported yet: the revocation cache (_BoundedRevocationCache) --
/// callers needing revocation must track that themselves for now.
/// </summary>
public static class TokenCodec
{
    public const string ConsentTokenPrefix = "HCT";
    public const long DefaultExpiryMs = 7L * 24 * 60 * 60 * 1000; // 7 days

    public static string Sign(string raw, string signingKey)
    {
        using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(signingKey));
        var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(raw));
        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    /// <summary>
    /// Issues a token with explicit issued/expires timestamps (ms since
    /// Unix epoch). Mirrors issue_token()'s raw-string construction and
    /// base64url encoding exactly.
    /// </summary>
    public static (string Token, string Signature) Issue(
        string userId,
        string agentId,
        string scope,
        long issuedAtMs,
        long expiresAtMs,
        bool commercial,
        string signingKey)
    {
        string raw = BuildRaw(userId, agentId, scope, issuedAtMs.ToString(), expiresAtMs.ToString(), commercial);
        string signature = Sign(raw, signingKey);
        string encoded = Base64UrlEncode(raw);
        string token = $"{ConsentTokenPrefix}:{encoded}.{signature}";
        return (token, signature);
    }

    /// <summary>
    /// Issues a token using the current time as issued_at, matching
    /// issue_token()'s default (expires_in_ms from now).
    /// </summary>
    public static (string Token, string Signature) Issue(
        string userId,
        string agentId,
        string scope,
        string signingKey,
        long expiresInMs = DefaultExpiryMs,
        bool commercial = false)
    {
        long issuedAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        return Issue(userId, agentId, scope, issuedAt, issuedAt + expiresInMs, commercial, signingKey);
    }

    /// <summary>
    /// Validates a token, mirroring validate_token()'s full signature and
    /// check ordering: revocation (fastest, checked before any parsing),
    /// then signature, then expiry (checked before scope so an expired
    /// token never leaks which scope it held), then scope (via
    /// ScopeMatcher.Matches, only if <paramref name="expectedScope"/> is
    /// given), then the commercial-flag gate. <paramref name="revocationCache"/>
    /// is optional -- omit it to skip revocation checking entirely (e.g. in
    /// tests), matching how most of the 71 existing call sites don't care
    /// about it.
    /// </summary>
    public static TokenValidationResult Validate(
        string tokenStr,
        string signingKey,
        string? expectedScope = null,
        bool? requireCommercial = null,
        RevocationCache? revocationCache = null)
    {
        if (revocationCache is not null && revocationCache.Contains(tokenStr))
            return TokenValidationResult.Invalid("Token has been revoked");

        var prefixParts = tokenStr.Split(':', 2);
        if (prefixParts.Length != 2)
            return TokenValidationResult.Invalid("Malformed token");

        string prefix = prefixParts[0];
        string signedPart = prefixParts[1];

        if (!signedPart.Contains('.'))
            return TokenValidationResult.Invalid("Malformed token");

        var signedParts = signedPart.Split('.', 2);
        string encoded = signedParts[0];
        string signature = signedParts[1];

        if (prefix != ConsentTokenPrefix)
            return TokenValidationResult.Invalid("Invalid token prefix");

        string decoded;
        try
        {
            decoded = Base64UrlDecode(encoded);
        }
        catch (FormatException)
        {
            return TokenValidationResult.Invalid("Malformed token");
        }

        string[] parts = decoded.Split('|');
        string userId, agentId, scope, issuedAtStr, expiresAtStr;
        bool commercial;

        if (parts.Length == 5)
        {
            (userId, agentId, scope, issuedAtStr, expiresAtStr) = (parts[0], parts[1], parts[2], parts[3], parts[4]);
            commercial = false;
        }
        else if (parts.Length == 6 && parts[5] == "commercial")
        {
            (userId, agentId, scope, issuedAtStr, expiresAtStr) = (parts[0], parts[1], parts[2], parts[3], parts[4]);
            commercial = true;
        }
        else
        {
            return TokenValidationResult.Invalid("Malformed token");
        }

        string raw = BuildRaw(userId, agentId, scope, issuedAtStr, expiresAtStr, commercial);
        string expectedSignature = Sign(raw, signingKey);

        if (!ConstantTimeEquals(signature, expectedSignature))
            return TokenValidationResult.Invalid("Invalid signature");

        if (!long.TryParse(issuedAtStr, out long issuedAt) || !long.TryParse(expiresAtStr, out long expiresAt))
            return TokenValidationResult.Invalid("Malformed token");

        // Expiry is checked before scope so an expired token never leaks
        // which scope it held to a caller who should only learn it expired.
        long nowMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        if (nowMs >= expiresAt)
            return TokenValidationResult.Invalid("Token expired");

        if (!string.IsNullOrEmpty(expectedScope) && !ScopeMatcher.Matches(scope, expectedScope))
            return TokenValidationResult.Invalid($"Scope mismatch: token has '{scope}', but '{expectedScope}' required");

        if (requireCommercial is true && !commercial)
            return TokenValidationResult.Invalid("Commercial consent required for this operation");
        if (requireCommercial is false && commercial)
            return TokenValidationResult.Invalid("Non-commercial consent required for this operation");

        var parsed = new ParsedConsentToken(userId, agentId, scope, issuedAt, expiresAt, signature, commercial);
        return TokenValidationResult.Valid(parsed);
    }

    private static string BuildRaw(string userId, string agentId, string scope, string issuedAt, string expiresAt, bool commercial)
    {
        return commercial
            ? $"{userId}|{agentId}|{scope}|{issuedAt}|{expiresAt}|commercial"
            : $"{userId}|{agentId}|{scope}|{issuedAt}|{expiresAt}";
    }

    /// <summary>hmac.compare_digest equivalent: constant-time, but still
    /// short-circuits on length like the Python stdlib does.</summary>
    private static bool ConstantTimeEquals(string a, string b)
    {
        byte[] aBytes = Encoding.UTF8.GetBytes(a);
        byte[] bBytes = Encoding.UTF8.GetBytes(b);
        if (aBytes.Length != bBytes.Length) return false;
        return CryptographicOperations.FixedTimeEquals(aBytes, bBytes);
    }

    internal static string Base64UrlEncode(string raw)
    {
        byte[] bytes = Encoding.UTF8.GetBytes(raw);
        return Convert.ToBase64String(bytes).Replace('+', '-').Replace('/', '_');
    }

    internal static string Base64UrlDecode(string encoded)
    {
        string standard = encoded.Replace('-', '+').Replace('_', '/');
        byte[] bytes = Convert.FromBase64String(standard);
        return Encoding.UTF8.GetString(bytes);
    }
}
